branches:
    - master
    - name: development
      prerelease: alpha
    - name: release-+([0-9]).+([0-9]).+([0-9])
      prerelease: fix
ci: false
tagFormat: ${version}
plugins:
    - @semantic-release/commit-analyzer
    - @semantic-release/release-notes-generator
    - @semantic-release/changelog
    - - @semantic-release/exec
      - prepareCmd: releaseScripts/prepare.sh ${nextRelease.version} ${branch.name} "${nextRelease.notes}"
    - @semantic-release/github
