VERSION 0.6
FROM node:16-alpine
WORKDIR /client

deps:
    COPY package.json package-lock.json ./
    COPY --dir patches ./
    RUN npm ci --ignore-scripts
    RUN npm run postinstall

build:
    FROM +deps
    COPY --dir src resources tslint.json tsconfig.json jest.config.js ./
    RUN npm run coverage
    COPY ../../server+build/server.jar ./server/
    COPY --dir syntaxes .vscodeignore CHANGELOG.md README.md snippets.json LICENSE ./
    RUN npm run package
    SAVE ARTIFACT *.vsix AS LOCAL ./
