/*
 * Copyright (c) 2026 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Broadcom - initial API and implementation
 */

import { IDocumentProcessingContext } from "@code4z/cobol-dialect-api";
import { SettingsService } from "./services/settings";

const SOURCE = "Generated by DaCo Dialect Support (Predefined Sections)";

export function generatePredefinedSections(
  context: IDocumentProcessingContext,
  sections: string[],
  procedureDivisionLine?: number,
) {
  if (!procedureDivisionLine || procedureDivisionLine < 0) {
    return;
  }
  const predefinedSection = new Set<string>(
    SettingsService.getPredefinedSections(),
  );

  sections.forEach((existing) => predefinedSection.delete(existing));
  if (predefinedSection.size === 0) {
    return;
  }
  let text = "";
  for (const section of predefinedSection) {
    text += generatePredefinedSection(section);
  }
  context.insert(procedureDivisionLine, text, SOURCE);
}

function generatePredefinedSection(section: string): string {
  return `       ${section} SECTION.\n           STOP RUN.\n`;
}
