import { generatePredefinedSections } from "../../../engine/predefined";
import { SettingsService } from "../../../engine/services/settings";

/*
 * Copyright (c) 2026 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Broadcom - initial API and implementation
 */
describe("Predefined sections test suite", () => {
  const context: any = {
    insert: jest.fn(),
  };

  beforeEach(() => {
    jest.clearAllMocks();
  });

  it("should not insert anything for empty predefined sections list", () => {
    jest
      .spyOn(SettingsService, "getPredefinedSections")
      .mockImplementation(() => []);

    generatePredefinedSections(context, [], 10);
    expect(context.insert).not.toHaveBeenCalled();
  });

  it("should not insert anything if procedure division was not found", () => {
    jest
      .spyOn(SettingsService, "getPredefinedSections")
      .mockImplementation(() => ["PREDEF0", "PREDEF1"]);

    generatePredefinedSections(context, [], undefined);
    expect(context.insert).not.toHaveBeenCalled();
  });

  it("should not insert anything when procedure division position is invalid", () => {
    jest
      .spyOn(SettingsService, "getPredefinedSections")
      .mockImplementation(() => ["PREDEF0", "PREDEF1"]);

    generatePredefinedSections(context, [], 0);
    expect(context.insert).not.toHaveBeenCalled();
  });

  it("should not insert anything if all sections are already defined", () => {
    jest
      .spyOn(SettingsService, "getPredefinedSections")
      .mockImplementation(() => ["PREDEF0", "PREDEF1"]);

    generatePredefinedSections(context, ["PREDEF0", "PREDEF1"], 10);
    expect(context.insert).not.toHaveBeenCalled();
  });

  it("should insert only missing section", () => {
    jest
      .spyOn(SettingsService, "getPredefinedSections")
      .mockImplementation(() => ["PREDEF0", "PREDEF1"]);

    generatePredefinedSections(context, ["PREDEF1"], 10);
    expect(context.insert).toHaveBeenCalledWith(
      10,
      "       PREDEF0 SECTION.\n           STOP RUN.\n",
      "Generated by DaCo Dialect Support (Predefined Sections)",
    );
  });
});
