VERSION 0.6
FROM maven:3-openjdk-8-slim
WORKDIR /server

deps:
    COPY pom.xml ./
    COPY --dir src/style ./src/style
    RUN mvn dependency:go-offline verify --no-transfer-progress
    RUN mvn clean

build:
    FROM +deps
    COPY --dir lombok.config src ./
    RUN mvn verify -B
    SAVE ARTIFACT target/server.jar server.jar
