VERSION 0.6
FROM maven:3-openjdk-8-slim
WORKDIR /server

listing:
    LOCALLY
    SAVE ARTIFACT ../Cobol85PositiveTestsSuite .

deps:
    COPY --dir +listing/Cobol85PositiveTestsSuite ./testFiles
    COPY pom.xml ./
    COPY --dir engine ./
    RUN mvn clean

build:
    FROM +deps
    RUN mvn -DfilesToTestPath=../testFiles -DlistingSnap=../testFiles/compileListing/snapshot clean verify --no-transfer-progress
    SAVE ARTIFACT engine/target/server.jar server.jar
