/*
 * Copyright (c) 2024 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *    Broadcom, Inc. - initial API and implementation
 *
 */
package org.eclipse.lsp.cobol.usecases;

import com.google.common.collect.ImmutableMap;
import org.eclipse.lsp.cobol.common.error.ErrorSource;
import org.eclipse.lsp.cobol.usecases.common.CICSTestUtils;
import org.eclipse.lsp4j.Diagnostic;
import org.eclipse.lsp4j.DiagnosticSeverity;
import org.eclipse.lsp4j.Range;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.Map;
import java.util.stream.Stream;

/**
 * Test CICS INQUIRE SP (System Programming Translator Option) commands. Documentation link: <a
 * href="https://www.ibm.com/docs/en/cics-ts/6.x?topic=commands-inquire-association">INQUIRE SP
 * Command</a>
 *
 * <p>This class tests all variations of the ISSUE command found in the link above.
 */
public class TestCICSInquireSP {

  private static final String INQUIRE_ASSOCIATION = "INQUIRE ASSOCIATION({$varOne})";

  private static final String INQUIRE_ASSOCIATION_ERROR = "INQUIRE {ASSOCIATION(101)|errorOne}";

  private static Stream<String> getValidOptions() {
    return Stream.of(
        "ASSOCIATION(1) CLNTIPFAMILY(1)",
        "ASSOCIATION LIST LISTSIZE(0) DNAME(1) DNAMELEN(2) REALM(3) REALMLEN(4) USERCORRDATA(5) SET(6)",
        "ATOMSERVICE(0) ATOMTYPE(1) CHANGEAGENT(2) ENABLESTATUS(3) INSTALLAGENT(4) RESOURCETYPE(5) BINDFILE(6) CHANGEAGREL(7) CHANGETIME(8) CHANGEUSRID(9) CONFIGFILE(10) DEFINESOURCE(11) DEFINETIME(12) INSTALLTIME(13) INSTALLUSRID(14) RESOURCENAME(15) URIMAP(16) XMLTRANSFORM(17)",
        "AUTINSTMODEL(0)",
        "AUTOINSTALL AIBRIDGE(0) CONSOLES(1) ENABLESTATUS(2) CURREQS(3) MAXREQS(4) PROGRAM(5)",
        "BRFACILITY(0) KEEPTIME(1) LINKSYSTEM(2) LINKSYSNET(3) NETNAME(4) REMOTESYSNET(5) REMOTESYSTEM(6) TASKID(7) TERMID(8) TRANSACTION(9) NAMESPACE(10) TERMSTATUS(11)",
        "BUNDLE(0) BUNDLEID(1) MAJORVERSION(2) MGMTPART(3) MICROVERSION(4) MINORVERSION(5) AVAILSTATUS(6) CHANGEAGENT(7) ENABLESTATUS(8) INSTALLAGENT(9) BASESCOPE(10) BUNDLEDIR(11) CHANGEAGREL(12) CHANGETIME(13) CHANGEUSRID(14) DEFINESOURCE(15) DEFINETIME(16) ENABLEDCOUNT(17) INSTALLTIME(18) INSTALLUSRID(19) PARTCOUNT(20) TARGETCOUNT(21)",
        "BUNDLEPART(0) BUNDLE(3) METADATAFILE(1) PARTTYPE(2) AVAILSTATUS(4) ENABLESTATUS(5) PARTCLASS(6)",
        "CAPDATAPRED NEXT CONTAINER(2) FIELDLENGTH(3) FIELDOFFSET(4) FILENAME(5) FILTERVALUE(6) LOCATION(7) STRUCTNAME(8) VARIABLENAME(9) OPERATOR(10)",
        "CAPINFOSRCE START CAPTURESPEC(0) EVENTBINDING(1)",
        "CAPOPTPRED NEXT FILTERVALUE(2) OPTIONNAME(3) OPERATOR(4)",
        "CAPTURESPEC(0) CAPTUREPOINT(1) CURRPGM(2) CURRTRANID(3) CURRUSERID(4) EVENTNAME(5) NUMDATAPRD(6) NUMINFOSRCE(7) NUMOPTPRED(8) PRIMPRED(9) EVENTBINDING(10) CAPTUREPTYPE(11) CURRPGMOP(12) CURRTRANIDOP(13) CURRUSERIDOP(14) PRIMPREDOP(15) PRIMPREDTYPE(16)",
        "CONNECTION(0) ACCESSMETHOD(1) ACQSTATUS(2) AUTOCONNECT(3) CHANGEAGENT(4) CONNSTATUS(5) CONNTYPE(6) CQP(7) EXITTRACING(8) INSTALLAGENT(9) PENDSTATUS(10) PROTOCOL(11) RECOVSTATUS(12) SERVSTATUS(13) XLNSTATUS(14) ZCPTRACING(15) AIDCOUNT(16) CHANGEAGREL(17) CHANGETIME(18) CHANGEUSRID(19) DEFINESOURCE(20) DEFINETIME(21) GRNAME(22) INSTALLTIME(23) INSTALLUSRID(24) LINKSYSTEM(25) MEMBERNAME(26) NETNAME(27) NQNAME(28) RECEIVECOUNT(29) REMOTENAME(30) REMOTESYSNET(31) REMOTESYSTEM(32) SENDCOUNT(33)",
        "CFDTPOOL(0) CONNSTATUS(1)",
        "DB2CONN ACCOUNTREC(0) AUTHTYPE(1) CHANGEAGENT(2) COMAUTHTYPE(3) CONNECTERROR(4) CONNECTST(5) DROLLBACK(6) INSTALLAGENT(7) NONTERMREL(8) PRIORITY(9) RESYNCMEMBER(10) STANDBYMODE(11) THREADERROR(12) THREADWAIT(13) AUTHID(14) CHANGEAGREL(15) CHANGETIME(16) CHANGEUSRID(17) COMAUTHID(18) COMTHREADLIM(19) COMTHREADS(20) DB2GROUPID(21) DB2ID(22) DB2RELEASE(23) DEFINESOURCE(24) DEFINETIME(25) INSTALLTIME(26) INSTALLUSRID(27) MSGQUEUE1(28) MSGQUEUE2(29) MSGQUEUE3(30) PLAN(31) PLANEXITNAME(32) PURGECYCLEM(33) PURGECYCLES(34) REUSELIMIT(35) SIGNID(36) STATSQUEUE(37) TCBLIMIT(38) TCBS(39) THREADLIMIT(40) THREADS(41)",
        "DB2ENTRY(0) ACCOUNTREC(1) AUTHTYPE(2) CHANGEAGENT(3) DISABLEDACT(4) DROLLBACK(5) ENABLESTATUS(6) INSTALLAGENT(7) PRIORITY(8) SHARELOCKS(9) THREADWAIT(10) AUTHID(11) CHANGEAGREL(12) CHANGETIME(13) CHANGEUSRID(14) DEFINESOURCE(15) DEFINETIME(16) INSTALLTIME(17) INSTALLUSRID(18) PLAN(19) PLANEXITNAME(20) PROTECTNUM(21) PTHREADS(22) THREADLIMIT(23) THREADS(24)",
        "DB2TRAN(0) DB2ENTRY(1) CHANGEAGREL(2) CHANGETIME(3) CHANGEUSRID(4) DEFINESOURCE(5) DEFINETIME(6) INSTALLTIME(7) INSTALLUSRID(8) PLAN(9) PLANEXITNAME(10) TRANSID(11) CHANGEAGENT(12) INSTALLAGENT(13)",
        "DELETSHIPPED IDLEHRS(1) IDLEMINS(2) IDLESECS(3) INTERVALHRS(5) INTERVALMINS(6) INTERVALSECS(7)",
        "DISPATCHER ACTOPENTCBS(0) ACTSSLTCBS(1) ACTTHRDTCBS(2) ACTXPTCBS(3) MAXOPENTCBS(4) MAXSSLTCBS(5) MAXTHRDTCBS(6) MAXXPTCBS(7) MROBATCH(8) PRTYAGING(9) RUNAWAY(10) SCANDELAY(11) SUBTASKS(12) TIME(13)",
        "DOCTEMPLATE(0) APPENDCRLF(1) CHANGEAGENT(2) INSTALLAGENT(3) TEMPLATETYPE(4) TYPE(5) CACHESIZE(6) CHANGEAGREL(7) CHANGETIME(8) CHANGEUSRID(9) DDNAME(10) DEFINESOURCE(11) DEFINETIME(12) DSNAME(13) EXITPGM(14) FILE(15) HFSFILE(16) INSTALLTIME(17) INSTALLUSRID(18) MEMBER(19) PROGRAM(20) TDQUEUE(21) TEMPLATENAME(22) TSQUEUE(23)",
        "DSNAME(0) ACCESSMETHOD(1) AVAILABILITY(2) BACKUPTYPE(3) OBJECT(4) LOGREPSTATUS(5) LOSTLOCKS(6) QUIESCESTATE(7) RECOVSTATUS(8) RETLOCKS(9) VALIDITY(10) BASEDSNAME(11) FILECOUNT(12) FWDRECOVLOG(13) FWDRECOVLSN(14)",
        "DUMPDS CURRENTDDS(0) INITIALDDS(1) OPENSTATUS(2) SWITCHSTATUS(3)",
        "ENQ NEXT UOW(3) DURATION(4) ENQFAILS(5) NETUOWID(6) QUALIFIER(7) QUALLEN(8) TASKID(11) TRANSID(12) RELATION(14) STATE(15) TYPE(16)",
        "ENQMODEL(0) CHANGEAGENT(1) INSTALLAGENT(2) STATUS(3) CHANGEAGREL(4) CHANGETIME(5) CHANGEUSRID(6) DEFINESOURCE(7) DEFINETIME(8) ENQSCOPE(9) ENQNAME(10) INSTALLTIME(11) INSTALLUSRID(12)",
        "EPADAPTER(0) ADAPTERTYPE(1) AUTHORITY(2) DATAFORMAT(3) EMITMODE(4) ENABLESTATUS(5) INVOKETYPE(6) PRIORITY(7) TRANSMODE(8) CHANGEAGENT(9) INSTALLAGENT(10) AUTHUSERID(11) CONFIGDATA1(12) PROGRAM(13) TRANSACTION(14) CHANGEAGREL(15) CHANGETIME(16) CHANGEUSRID(17) DEFINESOURCE(18) DEFINETIME(19) INSTALLTIME(20) INSTALLUSRID(21)",
        "EPADAPTERSET(0) EPADAPTERNUM(1) CHANGEAGREL(2) CHANGETIME(3) CHANGEUSRID(4) DEFINESOURCE(5) DEFINETIME(6) INSTALLTIME(7) INSTALLUSRID(8) ENABLESTATUS(9) CHANGEAGENT(10) INSTALLAGENT(11)",
        "EPADAPTINSET EPADAPTERSET(0) EPADAPTER(1)",
        "EVENTBINDING(0) CHANGEAGENT(1) ENABLESTATUS(2) EPADAPTERRES(3) INSTALLAGENT(4) CHANGEAGREL(5) CHANGETIME(6) CHANGEUSRID(7) DEFINESOURCE(8) DEFINETIME(9) EPADAPTER(10) EPADAPTERSET(11) INSTALLTIME(12) INSTALLUSRID(13) USERTAG(14)",
        "EVENTPROCESS EPSTATUS(0) SCHEMALEVEL(1)",
        "EXCI(0) TASK(1) UTIL(2)",
        "EXITPROGRAM(0) EXIT(1) ENTRYNAME(2) GAENTRYNAME(3) GALENGTH(4) GAUSECOUNT(5) NUMEXITS(6) QUALIFIER(7) TALENGTH(8) USECOUNT(9) APIST(10) CONCURRENTST(11) CONNECTST(12) FORMATEDFST(13) INDOUBTST(14) PURGEABLEST(15) SHUTDOWNST(16) SPIST(17) STARTSTATUS(18) TASKSTARTST(19) ENTRY(20)",
        "FEATUREKEY(0) VALUE(1) FILEPATH(2)",
        "FILE(0) ACCESSMETHOD(1) ADD(2) BLOCKFORMAT(3) BROWSE(4) CHANGEAGENT(5) DELETE(6) DISPOSITION(7) EMPTYSTATUS(8) ENABLESTATUS(9) EXCLUSIVE(10) FWDRECSTATUS(11) INSTALLAGENT(12) LOADTYPE(13) OBJECT(14) OPENSTATUS(15) RBATYPE(16) READ(17) READINTEG(18) RECORDFORMAT(19) RECOVSTATUS(20) RELTYPE(21) REMOTETABLE(22) RLSACCESS(23) TABLE(24) TYPE(25) UPDATE(26) UPDATEMODEL(27) BASEDSNAME(28) BLOCKKEYLEN(29) BLOCKSIZE(30) CFDTPOOL(31) CHANGEAGREL(32) CHANGETIME(33) CHANGEUSRID(34) DEFINESOURCE(35) DEFINETIME(36) DSNAME(37) INSTALLTIME(38) INSTALLUSRID(39) JOURNALNUM(40) KEYLENGTH(41) KEYPOSITION(42) LSRPOOLNUM(43) MAXNUMRECS(44) RECORDSIZE(45) REMOTENAME(46) REMOTESYSTEM(47) STRINGS(48) TABLENAME(49)",
        "HOST(0) TCPIPSERVICE(1) ENABLESTATUS(2)",
        "IPCONN(0) AUTOCONNECT(1) CHANGEAGENT(2) CONNSTATUS(3) HA(4) HOSTTYPE(5) IDPROP(6) IPFAMILY(7) INSTALLAGENT(8) LINKAUTH(9) MIRRORLIFE(10) PENDSTATUS(11) RECOVSTATUS(12) SERVSTATUS(13) SSLTYPE(14) USERAUTH(15) APPLID(16) CERTIFICATE(17) CHANGEAGREL(18) CHANGETIME(19) CHANGEUSRID(20) CIPHERS(21) CLIENTLOC(22) DEFINESOURCE(23) DEFINETIME(24) HOST(25) IPRESOLVED(26) INSTALLTIME(27) INSTALLUSRID(28) MAXQTIME(29) NETWORKID(30) NUMCIPHERS(31) PARTNER(32) PORT(33) QUEUELIMIT(34) RECEIVECOUNT(35) SECURITYNAME(36) SENDCOUNT(37) TCPIPSERVICE(38)",
        "IPFACILITY(0) IPCONN(1) IPFACILTYPE(2)",
        "IRC OPENSTATUS(0) XCFGROUP(1)",
        "JOURNALMODEL(0) CHANGEAGENT(1) INSTALLAGENT(2) TYPE(3) CHANGEAGREL(4) CHANGETIME(5) CHANGEUSRID(6) DEFINESOURCE(7) DEFINETIME(8) INSTALLTIME(9) INSTALLUSRID(10) JOURNALNAME(11) STREAMNAME(12)",
        "JOURNALNAME(0) STATUS(1) TYPE(2) STREAMNAME(3)",
        "JVMENDPOINT(0) JVMSERVER(1) TYPE(2) PORT(3) SECPORT(4) HOST(5) ENABLESTATUS(6)",
        "JVMSERVER(0) CHANGEAGENT(1) ENABLESTATUS(2) INSTALLAGENT(3) CHANGEAGREL(4) CHANGETIME(5) CHANGEUSRID(6) CURRENTHEAP(7) DEFINESOURCE(8) DEFINETIME(9) GCPOLICY(10) INITHEAP(11) INSTALLTIME(12) INSTALLUSRID(13) JAVAHOME(14) JVMPROFILE(15) LERUNOPTS(16) LOG(17) MAXHEAP(18) OCCUPANCY(19) PID(20) PROFILE(21) PROFILEDIR(22) STDERR(23) STDOUT(24) THREADCOUNT(25) THREADLIMIT(26) TRACE(27) WORKDIR(28)",
        "LIBRARY(0) APPLICATION(1) APPLMAJORVER(2) APPLMINORVER(3) APPLMICROVER(4) CHANGEAGREL(5) CHANGETIME(6) CHANGEUSRID(7) DEFINESOURCE(8) DEFINETIME(9) DSNAME01(10) DSNAME02(11) DSNAME03(12) DSNAME04(13) DSNAME05(14) DSNAME06(15) DSNAME07(16) DSNAME08(17) DSNAME09(18) DSNAME10(19) DSNAME11(20) DSNAME12(21) DSNAME13(22) DSNAME14(23) DSNAME15(24) DSNAME16(25) INSTALLUSRID(26) INSTALLTIME(27) NUMDSNAMES(28) PLATFORM(29) RANKING(30) SEARCHPOS(31) CHANGEAGENT(32) CRITICALST(33) ENABLESTATUS(34) INSTALLAGENT(35) DSNAMELIST(36)",
        "MODENAME(0) CONNECTION(1) ACTIVE(2) AVAILABLE(3) MAXIMUM(4) MAXWINNERS(5) AUTOCONNECT(6)",
        "MONITOR APPLNAMEST(0) COMPRESSST(1) CONVERSEST(2) EXCEPTCLASS(3) IDNTYCLASS(4) PERFCLASS(5) RESRCECLASS(6) RMIST(7) STATUS(8) SYNCPOINTST(9) TIME(10) DPLLIMIT(11) FILELIMIT(12) FREQUENCY(13) FREQUENCYHRS(14) FREQUENCYMINS(15) FREQUENCYSECS(16) TSQUEUELIMIT(17) URIMAPLIMIT(18) WEBSERVLIMIT(19)",
        "MQCONN CHANGEAGENT(0) CONNECTST(1) INSTALLAGENT(2) RESYNCNUMBER(3) CHANGEAGREL(4) CHANGETIME(5) CHANGEUSRID(6) DEFINESOURCE(7) DEFINETIME(8) INSTALLTIME(9) INSTALLUSRID(10) MQNAME(11) MQQMGR(12) MQRELEASE(13) TASKS(14) TRIGMONTASKS(15)",
        "MQINI(0) CHANGEAGENT(1) INSTALLAGENT(2) CHANGEAGREL(3) CHANGETIME(4) CHANGEUSRID(5) DEFINESOURCE(6) DEFINETIME(7) INITQNAME(8) INSTALLTIME(9) INSTALLUSRID(10)",
        "MQMONITOR(0) CHANGEAGENT(2) ENABLESTATUS(3) INSTALLAGENT(4) MONSTATUS(5) CHANGEAGREL(6) CHANGETIME(7) CHANGEUSRID(8) DEFINESOURCE(9) DEFINETIME(10) INSTALLTIME(11) INSTALLUSRID(12) MONDATA(13) MONUSERID(14) QNAME(15) TASKID(16) TRANSACTION(17) USERID(18)",
        "MVSTCB(1) NEXT SET(1) NUMELEMENTS(2)",
        "NODEJSAPP(0) TERMINAL(1) BUNDLE(2) CHANGEAGREL(3) CHANGETIME(4) CHANGEUSRID(5) DEFINESOURCE(6) DEFINETIME(7) INSTALLTIME(8) INSTALLUSRID(9) LERUNOPTS(10) LOG(11) NODEHOME(12) PID(13) PROFILE(14) STARTSCRIPT(15) STDERR(16) STDOUT(17) TRACE(18) CHANGEAGENT(19) ENABLESTATUS(20) INSTALLAGENT(21)",
        "OSGIBUNDLE(0) OSGIVERSION(1) JVMSERVER(2) BUNDLE(3) BUNDLEPART(4) CHANGEAGREL(5) CHANGETIME(6) CHANGEUSRID(7) DEFINESOURCE(8) DEFINETIME(9) INSTALLTIME(10) INSTALLUSRID(11) OSGIBUNDLEID(12) CHANGEAGENT(13) INSTALLAGENT(14) OSGISTATUS(15)",
        "OSGISERVICE(0) JVMSERVER(1) BUNDLE(2) BUNDLEPART(3) OSGIBUNDLE(4) OSGIVERSION(5) SRVCNAME(6) SRVCSTATUS(7)",
        "PARTNER(0) NETWORK(1) NETNAME(2) PROFILE(3) TPNAME(4) TPNAMELEN(5)",
        "PIPELINE(0) CHANGEAGENT(1) ENABLESTATUS(2) INSTALLAGENT(3) MODE(4) MTOMNOXOPST(5) MTOMST(6) SENDMTOMST(7) XOPDIRECTST(8) XOPSUPPORTST(9) CHANGEAGREL(10) CHANGETIME(11) CHANGEUSRID(12) CIDDOMAIN(13) CONFIGFILE(14) DEFINESOURCE(15) DEFINETIME(16) INSTALLTIME(17) INSTALLUSRID(18) MSGFORMAT(19) RESPWAIT(20) SHELF(21) SOAPLEVEL(22) SOAPRNUM(23) SOAPVNUM(24) WSDIR(25)",
        "POLICY(0) BUNDLE(1) CHANGEAGREL(2) CHANGETIME(3) CHANGEUSRID(4) DEFINESOURCE(5) DEFINETIME(6) INSTALLTIME(7) INSTALLUSRID(8) USERTAG(9) CHANGEAGENT(10) ENABLESTATUS(11) INSTALLAGENT(12)",
        "POLICYRULE(0) POLICY(1) ABENDCODE(2) ACTIONCOUNT(3) EPADAPTER(4) EPADAPTERSET(5) LASTACTTIME(6) RULEITEM(7) THRESHOLD(8) ACTIONTYPE(9) RULEGROUP(10) RULETYPE(11) WLMOPENST(12)",
        "PROCESSTYPE(0) AUDITLOG(1) CHANGEAGREL(2) CHANGETIME(3) CHANGEUSRID(4) DEFINESOURCE(5) DEFINETIME(6) FILE(7) INSTALLTIME(8) INSTALLUSRID(9) AUDITLEVEL(10) CHANGEAGENT(11) INSTALLAGENT(12) STATUS(13)",
        "PROFILE(0) CHANGEAGENT(1) INSTALLAGENT(2) CHANGEAGREL(3) CHANGETIME(4) CHANGEUSRID(5) DEFINESOURCE(6) DEFINETIME(7) INSTALLTIME(8) INSTALLUSRID(9)",
        "PROGRAM(0) APIST(1) CEDFSTATUS(2) CHANGEAGENT(3) COBOLTYPE(4) COPY(5) CONCURRENCY(6) DATALOCATION(7) DYNAMSTATUS(8) EXECKEY(9) EXECUTIONSET(10) HOLDSTATUS(11) INSTALLAGENT(12) LANGDEDUCED(13) LANGUAGE(14) LPASTATUS(15) PROGTYPE(16) REPLICATION(17) RESIDENCY(18) RUNTIME(19) SHARESTATUS(20) STATUS(21) APPLICATION(22) APPLMAJORVER(23) APPLMINORVER(24) APPLMICROVER(25) CHANGEAGREL(26) CHANGETIME(27) CHANGEUSRID(28) DEFINESOURCE(29) DEFINETIME(30) INSTALLTIME(31) INSTALLUSRID(32) JVMCLASS(33) JVMPROFILE(34) JVMSERVER(35) LENGTH(36) LIBRARY(37) LIBRARYDSN(38) OPERATION(39) PLATFORM(40) REMOTENAME(41) REMOTESYSTEM(42) RESCOUNT(43) TRANSID(44) USECOUNT(45) ENTRYPOINT(46) LOADPOINT(47)",
        "REQID(0) AFTER REQTYPE(1) FMHSTATUS(2) SET(3) TERMID(4) TRANSID(5) TIME(6) HOURS(8) MINUTES(9) SECONDS(10) LENGTH(11) RTRANSID(12) RTERMID(13) QUEUE(14) USERID(15)",
        "RRMS OPENSTATUS(0)",
        "SECDISCOVERY STATUS(0) CMD(1) DB2(2) DCT(3) FCT(4) HFS(5) JCT(6) PCT(7) PPT(8) PSB(9) RES(10) TRAN(11) TST(12) USER(13) LATSECDTIME(14) LASTWRITTIME(15) SECDCOUNT(16) NEWSECDCOUNT(17)",
        "SECRECORDING(0) ODADPTRID(1) ODADPTRDATA1(2) ODADPTRDATA2(3) ODADPTRDATA3(4) ODAPPLID(5) ODCLNTIPADDR(6) ODCLNTPORT(7) ODFACILNAME(8) ODFACILTYPE(9) ODIPFAMILY(10) ODLUNAME(11) ODNETID(12) ODNETWORKID(13) ODSERVERPORT(14) ODTCPIPS(15) ODTRANSID(16) ODUSERID(17) MAXIMUM(18) CURRENT(19)",
        "STATISTICS RECORDING(0) ENDOFDAY(1) ENDOFDAYHRS(2) ENDOFDAYMINS(3) ENDOFDAYSECS(4) INTERVAL(5) INTERVALHRS(6) INTERVALMINS(7) INTERVALSECS(8) NEXTTIME(9) NEXTTIMEHRS(10) NEXTTIMEMINS(11) NEXTTIMESECS(12)",
        "STORAGE ADDRESS(0) ELEMENT(1) ELEMENTLIST(2) LENGTHLIST(3) FLENGTH(4) NUMELEMENTS(5) TASK(6)",
        "STORAGE64 ELEMENT64(0) ELEMENTLIST(1) LENGTHLIST(2) ADRESS64(3) DSANAME(4) TASK(5) FLENGTH(6) NUMELEMENTS(7)",
        "STREAMNAME(0) STATUS(1) SYSTEMLOG(2) USECOUNT(3)",
        "SUBPOOL(0) DSANAME(1)",
        "SYSDUMPCODE(0) CHANGEAGENT(1) DAEOPTION(2) DUMPSCOPE(3) INSTALLAGENT(4) SHUTOPTION(5) SYSDUMPING(6) CHANGEAGREL(7) CHANGETIME(8) CHANGEUSRID(9) CURRENT(10) DEFINESOURCE(11) DEFINETIME(12) DSPLIST(13) INSTALLTIME(14) INSTALLUSRID(15) JOBLIST(16) MAXIMUM(17)",
        "SYSTEM ACTOPENTCBS(0) AIDCOUNT(1) AKP(2) CDSASIZE(3) CICSSYS(4) CICSTSLEVEL(5) DB2CONN(6) DFLTUSER(7) DSALIMIT(8) DSRTPROGRAM(9) DTRPROGRAM(10) ECDSASIZE(11) EDSALIMIT(12) EPCDSASIZE(13) EPUDSASIZE(14) ERDSASIZE(15) ESDSASIZE(16) EUDSASIZE(17) GCDSASIZE(18) GMMTEXT(19) GMMLENGTH(20) GSDSASIZE(21) GUDSASIZE(22) GMMTRANID(23) JOBNAME(24) LASTCOLDTIME(25) LASTEMERTIME(26) LASTINITTIME(27) LASTWARMTIME(28) LOGDEFER(29) MAXOPENTCBS(30) MAXTASKS(31) MEMLIMIT(32) MQCONN(33) MROBATCH(34) MVSSMFID(35) MVSSYSNAME(36) OPREL(37) OPSYS(38) OSLEVEL(39) PCDSASIZE(40) PLTPIUSR(41) PROGAUTOEXIT(42) PRTYAGING(43) PUDSASIZE(44) RDSASIZE(45) REGIONUSERID(46) RELEASE(47) RUNAWAY(48) SCANDELAY(49) SDSASIZE(50) SDTMEMLIMIT(51) SDTRAN(52) STARTUPDATE(53) TIME(54) UDSASIZE(55) SRRTASKS(56) CICSSTATUS(57) CMDPROTECT(58) COLDSTATUS(59) DEBUGTOOL(60) DUMPING(61) FORCEQR(62) HEALTHCHECK(63) INITSTATUS(64) MESSAGECASE(65) PROGAUTOCTLG(66) PROGAUTOINST(67) REENTPROTECT(68) RLSSTATUS(69) SECURITYMGR(70) SHUTSTATUS(71) SOSABOVEBAR(72) SOSABOVELINE(73) SOSBELOWLINE(74) SOSSTATUS(75) STARTUP(76) STOREPROTECT(77) TRANISOLATE(78) XRFSTATUS(79)",
        "TAG START NEXT END",
        "TASK ACTIVITY(0) ACTIVITYID(1) ATTACHTIME(2) BRFACILITY(3) BRIDGE(4) CURRENTPROG(5) DB2PLAN(6) DTIMEOUT(7) FACILITY(8) IDENTIFIER(9) INDOUBTMINS(10) IPFLISTSIZE(11) PRIORITY(12) PROCESS(13) PROCESSTYPE(14) PROFILE(15) PROGRAM(16) REMOTENAME(17) REMOTESYSTEM(18) RTIMEOUT(19) RUNAWAY(20) STARTCODE(21) SUSPENDTIME(22) SUSPENDTYPE(23) SUSPENDVALUE(24) RESNAME(25) TRANCLASS(26) TCLASS(27) TRANPRIORITY(28) TRANSACTION(29) TRPROF(30) TWASIZE(31) UOW(32) USERID(33) CMDSEC(34) DUMPING(35) FACILITYTYPE(36) INDOUBT(37) INDOUBTWAIT(38) ISOLATEST(39) PURGEABILITY(40) RESSEC(41) ROUTING(42) RUNSTATUS(43) SCRNSIZE(44) SRRSTATUS(45) STORAGECLEAR(46) TASKDATAKEY(47) TASKDATALOC(48) TCB(49) TRACING(50) IPFACILITIES(51)",
        "TASK LIST DISPATCHABLE RUNNING SUSPENDED LISTSIZE(0) SET(1) SETTRANSID(2)",
        "TCLASS(2) CURRENT(0) MAXIMUM(1)",
        "TCPIP ACTSOCKETS(0) CRLPROFILE(1) MAXSOCKETS(2) OPENSTATUS(3) SSLCACHE(4)",
        "TCPIPSERVICE(24) CERTIFICATE(0) CHANGEAGREL(1) CHANGETIME(2) CHANGEUSRID(3) CIPHERS(4) CLOSETIMEOUT(5) CONNECTIONS(6) DEFINESOURCE(7) DEFINETIME(8) GENERICTCPS(9) HOST(10) INSTALLTIME(11) INSTALLUSRID(12) IPADDRESS(13) IPRESOLVED(14) MAXDATALEN(15) MAXPERSIST(16) NUMCIPHERS(17) OPTIONSPGM(18) PORT(19) REALM(20) SPECIFTCPS(21) TRANSID(22) URM(23) BACKLOG(25) ATTACHSEC(26) ATTLS(27) AUTHENTICATE(28) CHANGEAGENT(29) HOSTTYPE(30) INSTALLAGENT(31) IPFAMILY(32) OPENSTATUS(33) PRIVACY(34) PROTOCOL(35) SOCKETCLOSE(36) SSLTYPE(37)",
        "TDQUEUE(14) ATITERMID(0) ATITRANID(1) ATIUSERID(2) BLOCKSIZE(3) DATABUFFERS(4) DDNAME(5) DSNAME(6) INDIRECTNAME(7) MEMBER(8) NUMITEMS(9) RECORDLENGTH(10) REMOTENAME(11) REMOTESYSTEM(12) TRIGGERLEVEL(13) ATIFACILITY(15) BLOCKFORMAT(16) DISPOSITION(17) EMPTYSTATUS(18) ENABLESTATUS(19) ERROROPTION(20) INDOUBT(21) INDOUBTWAIT(22) IOTYPE(23) OPENSTATUS(24) PRINTCONTROL(25) RECORDFORMAT(26) RECOVSTATUS(27) REWIND(28) SYSOUTCLASS(29) TYPE(30)",
        "TEMPSTORAGE TSMAININUSE(0) TSMAINLIMIT(1)",
        "TERMINAL(42) NETNAME(0) AIDCOUNT(1) ALTPAGEHT(2) ALTPAGEWD(3) ALTPRINTER(4) ALTSCRNHT(5) ALTSCRNWD(6) ALTSUFFIX(7) CONSOLE(8) CORRELID(9) DEFPAGEHT(10) DEFPAGEWD(11) DEFSCRNHT(12) DEFSCRNWD(13) GCHARS(14) GCODES(15) LINKSYSTEM(16) MAPNAME(17) MAPSETNAME(18) MODENAME(19) NATLANG(20) NEXTTRANSID(21) NQNAME(22) OPERID(23) PAGEHT(24) PAGEWD(25) PRINTER(26) REMOTENAME(27) REMOTESYSNET(28) REMOTESYSTEM(29) SCRNHT(30) SCRNWD(31) TASKID(32) TCAMCONTROL(33) TERMMODEL(34) TERMPRIORITY(35) TNADDR(36) TNPORT(37) TRANSACTION(38) USERAREALEN(39) USERID(40) USERNAME(41) ACCESSMETHOD(43) ACQSTATUS(44) ALTPRTCOPYST(45) APLKYBDST(46) APLTEXTST(47) ASCII(48) ATISTATUS(49) AUDALARMST(50) AUTOCONNECT(51) BACKTRANSST(52) COLORST(53) COPYST(54) CREATESESS(55) DATASTREAM(56) DEVICE(57) DISCREQST(58) DUALCASEST(59) EXITTRACING(60) EXTENDEDDSST(61) FMHPARMST(62) FORMFEEDST(63) HFORMST(64) HILIGHTST(65) KATAKANAST(66) LIGHTPENST(67) MSRCONTROLST(68) NATURE(69) OBFORMATST(70) OBOPERIDST(71) OUTLINEST(72) PAGESTATUS(73) PARTITIONSST(74) PRINTADAPTST(75) PROGSYMBOLST(76) PRTCOPYST(77) QUERYST(78) RELREQST(79) SECURITY(80) SERVSTATUS(81) SESSIONTYPE(82) SIGNONSTATUS(83) SOSIST(84) TERMSTATUS(85) TEXTKYBDST(86) TEXTPRINTST(87) TNIPFAMILY(88) TRACING(89) TTISTATUS(90) UCTRANST(91) VALIDATIONST(92) VFORMST(93) ZCPTRACING(94) USERAREA(95)",
        "TRACEDEST CURAUXDS(0) TABLESIZE(1) AUXSTATUS(2) GTFSTATUS(3) INTSTATUS(4) SWITCHSTATUS(5)",
        "TRACEFLAG SINGLESTATUS(0) SYSTEMSTATUS(1) TCEXITSTATUS(2) USERSTATUS(3)",
        "TRACETYPE SPECIAL STANDARD COMPID(0) FLAGSET(1)",
        "TRANCLASS(11) ACTIVE(0) MAXACTIVE(1) PURGETHRESH(2) QUEUED(3) CHANGEAGREL(4) CHANGETIME(5) CHANGEUSRID(6) DEFINESOURCE(7) DEFINETIME(8) INSTALLTIME(9) INSTALLUSRID(10) CHANGEAGENT(12) INSTALLAGENT(13) PURGEACTION(14)",
        "TRANDUMPCODE(9) CURRENT(0) MAXIMUM(1) CHANGEAGREL(2) CHANGETIME(3) CHANGEUSRID(4) DEFINESOURCE(5) DEFINETIME(6) INSTALLTIME(7) INSTALLUSRID(8) DUMPSCOPE(10) SHUTOPTION(11) SYSDUMPING(12) TRANDUMPING(13) CHANGEAGENT(14) INSTALLAGENT(15)",
        "TRANSACTION(23) BREXIT(0) DTIMEOUT(1) FACILITYLIKE(2) INDOUBTMINS(3) OTSTIMEOUT(4) PRIORITY(5) PROFILE(6) PROGRAM(7) REMOTENAME(8) REMOTESYSTEM(9) RTIMEOUT(10) RUNAWAY(11) TCLASS(12) TRANCLASS(13) TRPROF(14) TWASIZE(15) CHANGEAGREL(16) CHANGETIME(17) CHANGEUSRID(18) DEFINESOURCE(19) DEFINETIME(20) INSTALLTIME(21) INSTALLUSRID(22) APPLICATION(24) APPLMAJORVER(25) APPLMICROVER(26) APPLMINORVER(27) OPERATION(28) PLATFORM(29) AVAILSTATUS(30) CMDSEC(31) DUMPING(32) INDOUBT(33) INDOUBTWAIT(34) ISOLATEST(35) PURGEABILITY(36) RESSEC(37) ROUTING(38) ROUTESTATUS(39) RUNAWAYTYPE(40) SCRNSIZE(41) SHUTDOWN(42) STATUS(43) STORAGECLEAR(44) TASKDATAKEY(45) TASKDATALOC(46) TRACING(47) CHANGEAGENT(48) INSTALLAGENT(49)",
        "TSMODEL(13) CHANGEAGREL(0) CHANGETIME(1) CHANGEUSRID(2) DEFINESOURCE(3) DEFINETIME(4) EXPIRYINT(5) EXPIRYINTMIN(6) INSTALLTIME(7) INSTALLUSRID(8) POOLNAME(9) PREFIX(10) REMOTEPREFIX(11) REMOTESYSTEM(12) CHANGEAGENT(14) INSTALLAGENT(15) LOCATION(16) RECOVSTATUS(17) SECURITYST(18)",
        "TSPOOL(0) CONNSTATUS(1)",
        "TSQUEUE(8) EXPIRYINT(0) EXPIRYINTMIN(1) FLENGTH(2) LASTUSEDINT(3) MAXITEMLEN(4) MINITEMLEN(5) NUMITEMS(6) TRANSID(7) POOLNAME(10) TSMODEL(12) LOCATION(13) RECOVSTATUS(14)",
        "UOW(0) AGE(1) LINK(2) NETNAME(3) NETUOWID(4) OTSTID(5) SYSID(6) TASKID(7) TERMID(8) TRANSID(9) USERID(10) UOWSTATE(11) WAITCAUSE(12) WAITSTATE(13)",
        "UOWDSNFAIL NEXT DSNAME(0) NETNAME(1) SYSID(2) UOW(3) CAUSE(4) REASON(5) RLSACCESS(6)",
        "UOWENQ NEXT DURATION(0) ENQFAILS(1) NETUOWID(2) QUALIFIER(3) QUALLEN(4) TASKID(7) TRANSID(8) RESOURCE(11) RESLEN(12) RELATION(14) STATE(15) TYPE(16)",
        "UOWLINK(0) HOST(1) PORT(2) BRANCHQUAL(3) LINK(4) NETUOWID(5) RMIQFY(6) SYSID(7) UOW(8) URID(9) XID(10) PROTOCOL(11) RESYNCSTATUS(12) ROLE(13) TYPE(14)",
        "URIMAP(30) ATOMSERVICE(0) CERTIFICATE(1) CHANGEAGREL(2) CHANGETIME(3) CHANGEUSRID(4) CHARACTERSET(5) CIPHERS(6) CONVERTER(7) DEFINESOURCE(8) DEFINETIME(9) HFSFILE(10) HOST(11) HOSTCODEPAGE(12) INSTALLTIME(13) INSTALLUSRID(14) IPRESOLVED(15) LOCATION(16) MEDIATYPE(17) NUMCIPHERS(18) PATH(19) PIPELINE(20) PORT(21) PROGRAM(22) SOCKETCLOSE(23) SOCKPOOLSIZE(24) TCPIPSERVICE(25) TEMPLATENAME(26) TRANSACTION(27) USERID(28) WEBSERVICE(29) APPLICATION(31) APPLMAJORVER(32) APPLMINORVER(33) APPLMICROVER(34) OPERATION(35) PLATFORM(36) ANALYZERSTAT(37) AUTHENTICATE(38) AVAILSTATUS(39) CHANGEAGENT(40) ENABLESTATUS(41) HOSTTYPE(42) INSTALLAGENT(43) IPFAMILY(44) REDIRECTTYPE(45) SCHEME(46) USAGE(47)",
        "VTAM GRNAME(0) PSDINTERVAL(1) PSDINTHRS(2) PSDINTMINS(3) PSDINTSECS(4) GRSTATUS(5) OPENSTATUS(6) PSTYPE(7)",
        "WEB GARBAGEINT(0) TIMEOUTINT(1)",
        "WEBSERVICE(31) ARCHIVEFILE(0) BINDING(1) CCSID(2) CHANGEAGREL(3) CHANGETIME(4) CHANGEUSRID(5) CONTAINER(6) DEFINESOURCE(7) DEFINETIME(8) ENDPOINT(9) INSTALLTIME(10) INSTALLUSRID(11) LASTMODTIME(12) MAPPINGLEVEL(13) MAPPINGRNUM(14) MAPPINGVNUM(15) MINRUNLEVEL(16) MINRUNRNUM(17) MINRUNVNUM(18) PIPELINE(19) PROGRAM(20) URIMAP(21) WSBIND(22) WSDLFILE(23) CHANGEAGENT(24) INSTALLAGENT(25) PGMINTERFACE(26) STATE(27) VALIDATIONST(28) XOPDIRECTST(29) XOPSUPPORTST(30)",
        "WLMHEALTH ADJUSTMENT(0) HEALTH(1) HEALTHABSTIM(2) INTERVAL(3) OPENSTATUS(4)",
        "XMLTRANSFORM(21)BUNDLE(0) CCSID(1) MAPPINGLEVEL(2) MAPPINGRNUM(3) MAPPINGVNUM(4) MINRUNLEVEL(5) MINRUNRNUM(6) MINRUNVNUM(7) XMLSCHEMA(8) XSDBIND(9) CHANGEAGREL(10) CHANGETIME(11) CHANGEUSRID(12) DEFINESOURCE(13) DEFINETIME(14) INSTALLTIME(15) INSTALLUSRID(16) VALIDATIONST(17) CHANGEAGENT(18) ENABLESTATUS(19) INSTALLAGENT(20)");
  }

  private static final String INVALID_BROWSE_BRFACILITY =
      "INQUIRE BRFACILITY{(1)|errorOne} START RESP(1) ";

  private static final String VALID_BROWSE_CONNECTION =
      "INQUIRE CONNECTION(1) ACCESSMETHOD(1) RESP(1)";

  private static final String INVALID_BROWSE_BRFACILITY_TWO =
      "INQUIRE BRFACILITY START {KEEPTIME|errorOne}(1) RESP(1)";

  private static final String VALID_CAPDATAPRED_START_BROWSE =
      "INQUIRE CAPDATAPRED CAPTURESPEC(1) EVENTBINDING(1) START";

  private static final String VALID_CAPDATAPRED_START_BROWSE_TWO =
      "INQUIRE CAPDATAPRED START CAPTURESPEC(1) EVENTBINDING(1)";

  private static final String INVALID_CAPDATAPRED =
      "INQUIRE {_CAPDATAPRED CAPTURESPEC(1) EVENTBINDING(1)|errorOne_}";

  private static final String INVALID_CAPDATAPRED_START_BROWSE =
      "INQUIRE {_CAPDATAPRED START|errorOne|errorTwo_}";

  private static final String INVALID_CAPDATAPRED_NEXT =
      "INQUIRE CAPDATAPRED NEXT {CAPTURESPEC|errorOne}(1) {EVENTBINDING|errorTwo}(1)";

  private static final String VALID_CAPDATAPRED_NEXT = "INQUIRE CAPDATAPRED NEXT CONTAINER(1)";

  private static final String VALID_CAPDATAPRED_NEXT_TWO = "INQUIRE CAPDATAPRED NEXT";

  private static final String INVALID_CAPDATAPRED_END =
      "INQUIRE CAPDATAPRED {CAPTURESPEC|errorOne}(1) {EVENTBINDING|errorTwo}(1) END";

  private static final String VALID_CAPDATAPRED_END = "INQUIRE CAPDATAPRED END";

  private static final String INVALID_CAPDATAPRED_START =
      "INQUIRE CAPDATAPRED START CAPTURESPEC(1) EVENTBINDING(1) {CONTAINER|errorOne}(1)";

  private static final String VALID_BUNDLEPART_NEXT = "INQUIRE BUNDLEPART(1) NEXT AVAILSTATUS(1)";

  private static final String VALID_BUNDLEPART_END = "INQUIRE BUNDLEPART END";

  private static final String INVALID_BUNDLEPART_NEXT =
      "INQUIRE {BUNDLEPART|errorOne} NEXT AVAILSTATUS(1)";

  private static final String INVALID_BUNDLEPART_START = "INQUIRE {_BUNDLEPART START|errorOne_}";

  private static final String VALID_CAPTURESPEC_START = "INQUIRE CAPTURESPEC START EVENTBINDING(1)";

  private static final String INVALID_CAPTURESPEC_START =
      "INQUIRE CAPTURESPEC{(1)|errorOne} START EVENTBINDING(1)";

  private static final String INVALID_FEATUREKEY_BROWSE =
      "INQUIRE FEATUREKEY START {VALUE|errorOne}(1) {FILEPATH|errorTwo}(1)";

  private static final String INVALID_BROWSING =
      "INQUIRE REQID {START|errorOne} {NEXT|errorTwo} {END|errorThree}";

  private static final String VALID_PROGRAM = "INQUIRE PROGRAM START AT(1)";

  @Test
  void testValidProgram() {
    CICSTestUtils.noErrorTest(VALID_PROGRAM, "SP");
  }

  @Test
  void testInvalidBrowsing() {
    Map<String, Diagnostic> expectedDiagnostics =
        ImmutableMap.of(
            "errorOne",
            new Diagnostic(
                new Range(),
                "Exactly one option required, options are mutually exclusive: START or END or NEXT",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()),
            "errorTwo",
            new Diagnostic(
                new Range(),
                "Exactly one option required, options are mutually exclusive: START or END or NEXT",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()),
            "errorThree",
            new Diagnostic(
                new Range(),
                "Exactly one option required, options are mutually exclusive: START or END or NEXT",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()));
    CICSTestUtils.errorTest(INVALID_BROWSING, expectedDiagnostics, "SP");
  }

  @Test
  void testInvalidFeaturekeyBrowse() {
    Map<String, Diagnostic> expectedDiagnostics =
        ImmutableMap.of(
            "errorOne",
            new Diagnostic(
                new Range(),
                "Invalid option or parameter provided: Accessory options not allowed when browsing with START or END",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()),
            "errorTwo",
            new Diagnostic(
                new Range(),
                "Invalid option or parameter provided: Accessory options not allowed when browsing with START or END",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()));
    CICSTestUtils.errorTest(INVALID_FEATUREKEY_BROWSE, expectedDiagnostics, "SP");
  }

  @Test
  void testInvalidCaptureSpecStart() {
    Map<String, Diagnostic> expectedDiagnostics =
        ImmutableMap.of(
            "errorOne",
            new Diagnostic(
                new Range(),
                "Invalid option or parameter provided: Parameter usage when browsing with START or END",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()));
    CICSTestUtils.errorTest(INVALID_CAPTURESPEC_START, expectedDiagnostics, "SP");
  }

  @Test
  void testValidCapturespecStart() {
    CICSTestUtils.noErrorTest(VALID_CAPTURESPEC_START, "SP");
  }

  @Test
  void testValidConnection() {
    CICSTestUtils.noErrorTest(VALID_BROWSE_CONNECTION, "SP");
  }

  @Test
  void testInvalidCapdatapredEnd() {
    Map<String, Diagnostic> expectedDiagnostics =
        ImmutableMap.of(
            "errorOne",
            new Diagnostic(
                new Range(),
                "Invalid option provided: CAPTURESPEC with END",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()),
            "errorTwo",
            new Diagnostic(
                new Range(),
                "Invalid option provided: EVENTBINDING with END",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()));
    CICSTestUtils.errorTest(INVALID_CAPDATAPRED_END, expectedDiagnostics, "SP");
  }

  @Test
  void tesstInvalidCapdatapredStart() {
    Map<String, Diagnostic> expectedDiagnostics =
        ImmutableMap.of(
            "errorOne",
            new Diagnostic(
                new Range(),
                "Invalid option or parameter provided: Accessory options not allowed when browsing with START or END",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()));
    CICSTestUtils.errorTest(INVALID_CAPDATAPRED_START, expectedDiagnostics, "SP");
  }

  @Test
  void testValidCapdatapredEnd() {
    CICSTestUtils.noErrorTest(VALID_CAPDATAPRED_END, "SP");
  }

  @Test
  void testInvalidBundlepartNext() {
    Map<String, Diagnostic> expectedDiagnostics =
        ImmutableMap.of(
            "errorOne",
            new Diagnostic(
                new Range(),
                "Invalid option or parameter provided: Missing required option parameter",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()));
    CICSTestUtils.errorTest(INVALID_BUNDLEPART_NEXT, expectedDiagnostics, "SP");
  }

  @Test
  void testInvalidBundlepartStart() {
    Map<String, Diagnostic> expectedDiagnostics =
        ImmutableMap.of(
            "errorOne",
            new Diagnostic(
                new Range(),
                "Missing required option: BUNDLE with START",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()));
    CICSTestUtils.errorTest(INVALID_BUNDLEPART_START, expectedDiagnostics, "SP");
  }

  @Test
  void testValidBundlePartNext() {
    CICSTestUtils.noErrorTest(VALID_BUNDLEPART_NEXT, "SP");
  }

  @Test
  void testValidBundlePartEnd() {
    CICSTestUtils.noErrorTest(VALID_BUNDLEPART_END, "SP");
  }

  @Test
  void testValidCapdatapredNext() {
    CICSTestUtils.noErrorTest(VALID_CAPDATAPRED_NEXT, "SP");
  }

  @Test
  void testValidCapdatapredNextTwo() {
    CICSTestUtils.noErrorTest(VALID_CAPDATAPRED_NEXT_TWO, "SP");
  }

  @Test
  void testInvalidCapdatapredNext() {
    Map<String, Diagnostic> expectedDiagnostics =
        ImmutableMap.of(
            "errorOne",
            new Diagnostic(
                new Range(),
                "Invalid option provided: CAPTURESPEC with NEXT",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()),
            "errorTwo",
            new Diagnostic(
                new Range(),
                "Invalid option provided: EVENTBINDING with NEXT",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()));
    CICSTestUtils.errorTest(INVALID_CAPDATAPRED_NEXT, expectedDiagnostics, "SP");
  }

  @Test
  void testValidCapdatapredStartBrowse() {
    CICSTestUtils.noErrorTest(VALID_CAPDATAPRED_START_BROWSE, "SP");
  }

  @Test
  void testValidCapdatapredStartBrowseTwo() {
    CICSTestUtils.noErrorTest(VALID_CAPDATAPRED_START_BROWSE_TWO, "SP");
  }

  @Test
  void testInvalidCapdatapred() {
    Map<String, Diagnostic> expectedDiagnostics =
        ImmutableMap.of(
            "errorOne",
            new Diagnostic(
                new Range(),
                "Exactly one option required, none provided: START or END or NEXT",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()));
    CICSTestUtils.errorTest(INVALID_CAPDATAPRED, expectedDiagnostics, "SP");
  }

  @Test
  void testInvalidCapdatapredStartBrowse() {
    Map<String, Diagnostic> expectedDiagnostics =
        ImmutableMap.of(
            "errorOne",
            new Diagnostic(
                new Range(),
                "Missing required option: CAPTURESPEC with START",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()),
            "errorTwo",
            new Diagnostic(
                new Range(),
                "Missing required option: EVENTBINDING with START",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()));
    CICSTestUtils.errorTest(INVALID_CAPDATAPRED_START_BROWSE, expectedDiagnostics, "SP");
  }

  @Test
  void testInquireAssociationValid() {
    CICSTestUtils.noErrorTest(INQUIRE_ASSOCIATION, "SP", "EXCI");
  }

  @Test
  void testInquireAssociationInValid() {
    Map<String, Diagnostic> expectedDiagnostics =
        ImmutableMap.of(
            "errorOne",
            new Diagnostic(
                new Range(),
                "Invalid CICS command without translator option: \"SP\"",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()));
    CICSTestUtils.errorTest(INQUIRE_ASSOCIATION_ERROR, expectedDiagnostics, "EXCI");
  }

  @ParameterizedTest
  @MethodSource("getValidOptions")
  void testOption(String cicsOption) {
    CICSTestUtils.noErrorTest("INQUIRE " + cicsOption, "SP");
  }

  @Test
  void testInquireBrowseInvalidOne() {
    Map<String, Diagnostic> expectedDiagnostics =
        ImmutableMap.of(
            "errorOne",
            new Diagnostic(
                new Range(),
                "Invalid option or parameter provided: Parameter usage when browsing with START or END",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()));
    CICSTestUtils.errorTest(INVALID_BROWSE_BRFACILITY, expectedDiagnostics, "SP");
  }

  @Test
  void testInquireBrowseInvalidTwo() {
    Map<String, Diagnostic> expectedDiagnostics =
        ImmutableMap.of(
            "errorOne",
            new Diagnostic(
                new Range(),
                "Invalid option or parameter provided: Accessory options not allowed when browsing with START or END",
                DiagnosticSeverity.Error,
                ErrorSource.PARSING.getText()));
    CICSTestUtils.errorTest(INVALID_BROWSE_BRFACILITY_TWO, expectedDiagnostics, "SP");
  }
}
