/*
 * Copyright (c) 2020 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *    Broadcom, Inc. - initial API and implementation
 *
 */

package org.eclipse.lsp.cobol.usecases;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import org.eclipse.lsp.cobol.positive.CobolText;
import org.eclipse.lsp.cobol.core.model.ErrorSource;
import org.eclipse.lsp.cobol.usecases.engine.UseCaseEngine;
import org.eclipse.lsp4j.Diagnostic;
import org.eclipse.lsp4j.DiagnosticSeverity;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * This test checks grammar does not consume more tokens than necessary in REPLACING statement.
 * Here: REPLACING statement for REPL is incorrect due to different pattern types, so this statement
 * must not be parsed. COPY is valid in WS section due to COPY IDMS addition.
 */
class TestReplacingWithDifferentPatternsShowsError {

  private static final String TEXT =
      "       IDENTIFICATION DIVISION.  \n"
          + "       PROGRAM-ID. TESTREPL.\n"
          + "       DATA DIVISION.\n"
          + "       WORKING-STORAGE SECTION.\n"
          + "       01  {$*PARENT} PIC 9.\n"
          + "       COPY {REPL|1} {REPLACING|2} ==TAG== BY DEF. \n"
          + "       PROCEDURE DIVISION.\n"
          + "       MAINLINE.\n"
          + "           PERFORM NAME3. \n"
          + "       COPY {~NEW2} REPLACING ==NAME2== BY ==NAME3== .\n"
          + "           GOBACK.";

  private static final String NEW2 =
      "         NAME2.\n" + "           DISPLAY \"ABC\".\n" + "           MOVE 0 TO PARENT. ";
  private static final String NEW2_NAME = "NEW2";

  private static final String MESSAGE = "Missing token IDMS at dataDescriptionEntryCopyIdms";

  private static final String MESSAGE2 =
      "Syntax error on 'REPLACING' expected {<EOF>, ASSOCIATED-DATA, ASSOCIATED-DATA-LENGTH, BOUNDS, CAPABLE, CCSVERSION, CICS, "
          + "CLOSE-DISPOSITION, COMMITMENT, CONVENTION, CRUNCH, DEFAULT-DISPLAY, DFHRESP, DFHVALUE, DISK, ENCODING, EXITS, "
          + "FUNCTION-POINTER, ID, IDENTIFICATION, IDMS, IGNORED, IMPLICIT, IN, INVOKED, KEPT, KEYBOARD, LIBRARY, LINKAGE, LOCAL-STORAGE, "
          + "LONG-DATE, LONG-TIME, LOWER, LTERM, LR, MAPS, NATIONAL-EDITED, NETWORK, NODENAME, NOWRITE, NUMERIC-DATE, NUMERIC-TIME, ODT, "
          + "ORDERLY, OWN, POINTER-32, PORT, PRINTER, PTERM, READER, RECEIVED, RECURSIVE, REDEFINES, REMOTE, SAVE, SCREENSIZE, SHORT-DATE,"
          + " SUBSCHEMA-AREANAMES, SUBSCHEMA-CONTROL, SUBSCHEMA-CTRL, SUBSCHEMA-DESCRIPTION, SUBSCHEMA-DML-LR-DESCRIPTION, "
          + "SUBSCHEMA-LR-CONTROL, SUBSCHEMA-LR-CTRL, SUBSCHEMA-LR-DESCRIPTION, SUBSCHEMA-LR-NAMES, SUBSCHEMA-LR-RECORDS, SUBSCHEMA-NAMES, "
          + "SUBSCHEMA-RECNAMES, SUBSCHEMA-RECORDS, SUBSCHEMA-SETNAMES, SUBSCHEMA-NAME, SYSVERSION, THREAD, THREAD-LOCAL, TODAYS-DATE, "
          + "TODAYS-NAME, TRUNCATED, TYPEDEF, UTF-8, VIRTUAL, WORKING-STORAGE, ABSOLUTE, ACCELERATION, ACCELERATOR, ACCESSCTRL, ACCTNG, "
          + "ACTIVATE, ACTIVE, ADA, AGE, ALGORITHM, ALIAS, ALLOW, ALTERIN, ALWAYS, APPEND, APPLCOMPAT, APPLICATION, APPLNAME, ARCHIVE, ARRAY,"
          + " ARRAY-EXISTS, ASC, ASCII, ASENSITIVE, ASSEMBLE, ASSERTION, ASSOCIATE, ASUTIME, ATOMIC, AUDIT, AUTHENTICATION, AUTHID, "
          + "AUTHORIZATION, AUTOMATIC, AUTONOMOUS, AUX, AVG, BASED, BEGIN, BETWEEN, BIGINT, BINARY-STRING-CONSTANT, BIND, BINDADD,"
          + " BINDAGENT, BIT-LENGTH, BLOB, BLOCKED, BOTH, BSDS, BUFFERPOOL, BUFFERPOOLS, BUSINESS-TIME, CACHE, CALLED, CALLER, CAPTURE, "
          + "CARDINALITY, CASCADE, CASCADED, CASE, CAST, CATALOG, CATALOG-NAME, CHANGED, CHANGES, CHAR-LENGTH, CHARACTER-LENGTH, CHECKED, "
          + "CLAUSE, CLIENT-ACCTNG, CLIENT-APPLNAME, CLIENT-CORR-TOKEN, CLIENT-USERID, CLIENT-WRKSTNNAME, CLOB, CLONE, CLUSTER, COALESCE, "
          + "COBOL, CODEUNITS32, COLLATE, COLLATION, COLLECT, COLLECTION, COLLID, COLUMNS, COMMENT, COMMIT, COMMITTED, COMPARISONS, "
          + "COMPATIBILITY, COMPRESS, CONCAT, CONCENTRATE, CONCURRENT, CONDITION-NUMBER, CONNECTION, CONNECTION-NAME, CONSERVATIVE, "
          + "CONSTANT, CONSTRAINT, CONSTRAINTS, CONTEXT, CONVERT, CORRELATION, COUNT, COUNT-BIG, COVARIANCE, CPU, CREATE-SECURE-OBJECT, "
          + "CREATEALIAS, CREATEDBA, CREATEDBC, CREATEIN, CREATESG, CREATETAB, CREATETMTAB, CREATETS, CROSS, CS, CUBE, CUME-DIST, "
          + "CURRENT-DATE, CURRENT-LC-CTYPE, CURRENT-PATH, CURRENT-SCHEMA, CURRENT-SERVER, CURRENT-SQLID, CURRENT-TIME, CURRENT-TIMESTAMP,"
          + " CURRENT-TIMEZONE, CURRENT-USER, CURRENTLY, CURSOR, CURSOR-NAME, CURSORS, CYCLE, DATAACCESS, DATABASE, DATACLAS, DATALINK, "
          + "DB2, DB2-AUTHENTICATION-TYPE, DB2-AUTHORIZATION-ID, DB2-CONNECTION-STATE, DB2-CONNECTION-STATUS, DB2-ENCRYPTION-TYPE, "
          + "DB2-ERROR-CODE1, DB2-ERROR-CODE2, DB2-ERROR-CODE3, DB2-ERROR-CODE4, DB2-GET-DIAGNOSTICS-DIAGNOSTICS, "
          + "DB2-INTERNAL-ERROR-POINTER, DB2-LAST-ROW, DB2-LINE-NUMBER, DB2-MESSAGE-ID, DB2-MODULE-DETECTING-ERROR, "
          + "DB2-NUMBER-PARAMETER-MARKERS, DB2-NUMBER-RESULT-SETS, DB2-NUMBER-ROWS, DB2-ORDINAL-TOKEN1, DB2-ORDINAL-TOKEN2, "
          + "DB2-ORDINAL-TOKEN3, DB2-ORDINAL-TOKEN4, DB2-PRODUCT-ID, DB2-REASON-CODE, DB2-RETURN-STATUS, DB2-RETURNED-SQLCODE, "
          + "DB2-ROW-NUMBER, DB2-SERVER-CLASS-NAME, DB2-SQL-ATTR-CURSOR-HOLD, DB2-SQL-ATTR-CURSOR-ROWSET, DB2-SQL-ATTR-CURSOR-SCROLLABLE, "
          + "DB2-SQL-ATTR-CURSOR-SENSITIVITY, DB2-SQL-ATTR-CURSOR-TYPE, DB2-SQL-NESTING-LEVEL, DB2-SQLERRD1, DB2-SQLERRD2, DB2-SQLERRD3, "
          + "DB2-SQLERRD4, DB2-SQLERRD5, DB2-SQLERRD6, DB2-SQLERRD-SET, DB2-TOKEN-COUNT, DB2DARI, DB2GENERAL, DB2GENRL, DB2SQL, DBADM, "
          + "DBCLOB, DBCTRL, DBINFO, DBMAINT, DEACTIVATE, DEADLOCKS, DEALLOCATE, DEBUG, DEBUGSESSION, DEC, DEC-ROUND-CEILING, DEC-ROUND-DOWN, "
          + "DEC-ROUND-FLOOR, DEC-ROUND-HALF-DOWN, DEC-ROUND-HALF-EVEN, DEC-ROUND-HALF-UP, DEC-ROUND-UP, DECFLOAT, DECIMAL, DECLARE, DEFAULT, "
          + "DEFAULTS, DEFER, DEFERRABLE, DEFERRED, DEFINEBIND, DEFINER, DEFINERUN, DEFINITION, DEGREE, DENSE-RANK, DEPENDENT, DESC, DESCRIBE,"
          + " DESCRIPTOR, DETERMINISTIC, DIAGNOSTICS, DIMENSIONS, DISALLOW, DISPATCH, DISPLAYDB, DISTINCT, DISTNCT, DO, DOMAIN, DOUBLE,"
          + " DOUBLEQUOTE, DPSEGSZ, DROP, DROPIN, DSNDB04, DSSIZE, DYNAMICRULES, EACH, EBCDIC, EDITPROC, ELEMENT, ELIGIBLE, ELSEIF, EMPTY,"
          + " ENCRYPTION, ENFORCED, ESCAPE, EUR, EXACT, EXCEPT, EXCHANGE, EXCLUDE, EXCLUDING, EXCLUSIVE, EXISTS, EXPLAIN, EXTENDED, "
          + "EXTENSION, EXTRA, FAILBACK, FAILURE, FAILURES, FEDERATED, FENCED, FETCH, FIELDPROC, FIRST-VALUE, FLOAT, FLUSH, FOLLOWING,"
          + " FOREIGN, FORMAT, FORTRAN, FOUND, FREEPAGE, FS, FULL, FUNCTION-LEVEL-10, FUNCTION-LEVEL-11, FUNCTION-LEVEL-12, G-CHAR, "
          + "GBPCACHE, GENERAL, GENERATED, GET-ACCEL-ARCHIVE, GOTO, GRANT, GRAPHIC, GROUPING, HANDLER, HASH, HAVING, HIDDENCHAR, HIGH,"
          + " HINT, HISTORY, HOUR, IDENTITY, IMAGCOPY, IMPLICIT-SCHEMA, IMPLICITLY, INCLUDING, INCLUSIVE, INDEXBP, INDEXES, INDICATOR, "
          + "INHERIT, INITIAL-INSTS, INITIAL-IOS, INITIALLY, INLINE, INNER, INOUT, INSENSITIVE, INSTEAD, INSTS-PER-ARGBYTE, "
          + "INSTS-PER-INVOC, INT, INTEGER, INTEGRITY, INTERSECT, INVOKEBIND, INVOKERUN, IOS-PER-ARGBYTE, IOS-PER-INVOC, ISO, "
          + "ISOLATION, ITERATE, JAR, JAVA, JIS, JOBNAME, JOIN, K-CHAR, KEYS, LABELS, LAG, LANGUAGE, LANGUAGE-C, LARGE, LAST-VALUE, "
          + "LC-CTYPE, LEAD, LEAVE, LIKE, LINKTYPE, LITERALS, LOB, LOCAL, LOCALE, LOCATION, LOCATOR, LOCATORS, LOCKED, LOCKMAX, LOCKS, "
          + "LOCKSIZE, LOGGED, LONG, LONGVAR, LOOP, LOW, QUOTED-NONE, M-CHAR, MAINTAINED, MAPPING, MASK, MATCH, MATCHED, MATERIALIZED, "
          + "MAX, MAXPARTITIONS, MAXROWS, MAXVALUE, MEMBER, MESSAGE-TEXT, MGMTCLAS, MICROSECOND, MICROSECONDS, MINUTE, MINVALUE, MIXED,"
          + " MODIFIERS, MODIFIES, MODULE, MONITOR1, MONITOR2, MONTHS, MORECHAR, MULTIPLIER, NAMED, NAMES, NAMESPACE, NATIONAL, NATURAL, "
          + "NCHAR, NEW, NEW-TABLE, NEXTVAL, NICKNAME, NOCACHE, NOCYCLE, NODE, NODEFER, NOMINVALUE, NOORDER, NTH-VALUE, NULLABLE, NULTERM, "
          + "NUMPARTS, OBID, OBJECT, OCTETS, OF, OFFSET, OLD, OLD-TABLE, OLE, OLEDB, ONCE, ONLINE, ONLY, OPTHINT, OPTIMIZATION, OPTIMIZE, "
          + "OPTION, ORDINALITY, ORGANIZE, ORIGINAL, OUT, OUTCOME, OUTER, OVER, OVERLAPS, OVERRIDING, OWNERSHIP, PACKADM, PACKAGE, "
          + "PACKAGE-NAME, PACKAGE-SCHEMA, PACKAGE-VERSION, PACKAGESET, PAD, PADDED, PARALLEL, PARAMETER, PART, PARTIAL, PARTITION, "
          + "PARTITIONED, PARTITIONING, PASCAL, PASSING, PASSTHRU, PCTFREE, PENDING, PERCENT-ARGBYTES, PERCENT-RANK, PERIOD, PERMISSION, "
          + "PIECESIZE, PIPE, PLAN, PLI, PORTION, POSITIONING, PRECEDING, PRECISION, PRESERVE, PREVIOUS, PRIMARY, PRIOR, PRIQTY, PRIVILEGES, "
          + "PROCEDURE, PROTOCOL, PUBLIC, QUALIFIER, QUERYNO, RANGE, RANK, RATIO-TO-REPORT, READS, REAL, RECOMMEND, RECOVERDB, RECOVERY, "
          + "REF, REFERENCING, REFRESH, REGENERATE, REGISTERS, RENAME, REOPT, REORG, REPAIR, REPEAT, REPLICATED, REQUIRED, RESIDENT,"
          + " RESIGNAL, RESOLUTION, RESOLVE, RESPECT, RESTORE, RESTRICT, RESULT-SET-LOCATOR, RETRUN, RETURN-STATUS, RETURNED-SQLSTATE,"
          + " RETURNS, REUSE, REVOKE, REXX, ROLLUP, ROTATE, ROUND-CEILING, ROUND-DOWN, ROUND-FLOOR, ROUND-HALF-DOWN, ROUND-HALF-EVEN, "
          + "ROUND-HALF-UP, ROUND-UP, ROUNDING, ROUTINE, ROW, ROW-COUNT, ROW-NUMBER, ROWID, ROWS, ROWSET, RR, RS, RULES, SAVEPOINT, SBCS,"
          + " SCALE, SCHEMA, SCRATCHPAD, SCROLL, SECOND, SECQTY, SECURED, SEGSIZE, SELECTIVITY, SENSITIVE, SEQUENCE, SERIALIZABLE, SERVAUTH,"
          + " SERVER-NAME, SESSION-USER, SETS, SHARE, SHRLEVEL, SIGNAL, SIMPLE, SKIPCHAR, SMALLINT, SNAPSHOT, SOME, SPECIAL, SPECIFIC, SQLADM,"
          + " SQLCA, SQLCODE, SQLD, SQLDA, SQLDABC, SQLERROR, SQLEXCEPTION, SQLID, SQLN, SQLSTATE, SQLVAR, SQLWARNING, STABILIZED, STACKED,"
          + " STARTDB, STARTING, STATEMENT, STATEMENTS, STATIC, STATISTICS, STATS, STAY, STDDEV, STMTCACHE, STMTID, STMTTOKEN, STOGROUP, "
          + "STOPALL, STOPDB, STORCLAS, STORED, STORES, STORIES, STOSPACE, STRUCTURE, STYLE, SUB, SUBSTR, SUBSTRING, SUMMARY, SWITCH, "
          + "SYNONYM, SYSADM, SYSCTRL, SYSDEFLT, SYSIBM, SYSOPR, SYSTEM, SYSTEM-TIME, SYSTEM-USER, TABLE, TABLE-NAME, TABLESPACE, "
          + "TABLESPACES, TEMPORAL, TEMPORARY, THREADSAFE, TIMESTAMP, TIMEZONE, TIMEZONE-HOUR, TIMEZONE-MINUTE, TRACKMOD, TRANSFER, "
          + "TRANSLATE, TRANSLATION, TREAT, TRIGGERS, TRIM, TRUNCATE, TRUSTED, TYPES, UNBOUNDED, UNDER, UNDO, UNICODE, UNION, "
          + "UNIQUE, UNKNOWN, UNNEST, UNPACK, UPPER, UR, USA, USER, V1, VALIDATE, VALIDPROC, VARBINARY, VARCHAR, VARGRAPHIC, "
          + "VARIABLE, VARIANCE, VARIANT, VCAT, VERSION, VERSIONING, VERSIONS, VIEW, VOLATILE, VOLUMES, WAITFORDATA, WHENEVER, "
          + "WHERE, WHILE, WITHOUT, WLM, WORK, WORKFILE, WRAPPED, WRAPPER, WRKSTNNAME, XMLCAST, XMLNAMESPACES, XMLPATTERN, "
          + "XMLSCHEMA, XMLTABLE, YEARS, YES, ZONE, ABCODE, ABDUMP, ABEND, ABORT, ABPROGRAM, ABSTIME, ACCUM, ACEE, "
          + "ACQACTIVITY, ACQPROCESS, ACQUACTIVITY, ACTION, ACTIVITY, ACTIVITYID, ACTPARTN, AID, ALARM, ALLOCATE, "
          + "ALTSCRNHT, ALTSCRNWD, ANYKEY, APLKYBD, APLTEXT, APPLID, AS, ASA, ASKTIME, ASRAINTRPT, ASRAKEY, ASRAPSW, "
          + "ASRAREGS, ASRASPC, ASRASTG, ASYNCHRONOUS, ATTACH, ATTACHID, ATTRIBUTES, AUTHENTICATE, AUTOPAGE, "
          + "AUXILIARY, BASE64, BASICAUTH, BELOW, BIF, BINARY, BIT, BODYCHARSET, BOOKMARK, BRDATA, BRDATALENGTH, "
          + "BREXIT, BRIDGE, BROWSETOKEN, BTRANS, BUFFER, BUILD, BURGEABILITY, CADDRLENGTH, CARD, CBUFF, CCSID, "
          + "CERTIFICATE, CHANGE, CHANGETIME, CHANNEL, CHAR, CHARACTERSET, CHECK, CHUNKEND, CHUNKING, CHUNKNO, "
          + "CHUNKYES, CICSDATAKEY, CIPHERS, CLEAR, CLICONVERT, CLIENT, CLIENTADDR, CLIENTADDRNU, CLIENTCONV, "
          + "CLIENTNAME, CLNTADDR6NU, CLNTIPFAMILY, CLOSESTATUS, CLRPARTN, CMDSEC, CNAMELENGTH, CNOTCOMPL, CODE, "
          + "CODEPAGE, COLOR, COMMAREA, COMMONNAME, COMMONNAMLEN, COMPAREMAX, COMPAREMIN, COMPLETE, COMPOSITE,"
          + " COMPSTATUS, CONDITION, CONFIRM, CONFIRMATION, CONNECT, CONSISTENT, CONSOLE, CONTAINER, CONTEXTTYPE, "
          + "CONVDATA, CONVERSE, CONVERTST, CONVERTTIME, CONVID, COPY, COUNTER, COUNTRY, COUNTRYLEN, CREATE, CRITICAL, "
          + "CTLCHAR, CURRENT, CWA, CWALENG, DATA1, DATA2, DATALENGTH, DATALENTH, DATAONLY, DATAPOINTER, DATASTR, DATATOXML, "
          + "DATATYPE, DATCONTAINER, DATEFORM, DATESEP, DATESTRING, DAYCOUNT, DAYOFMONTH, DAYOFWEEK, DAYOFYEAR, DAYS, DAYSLEFT, "
          + "DCOUNTER, DDMMYY, DDMMYYYY, DEBKEY, DEBREC, DEEDIT, DEFINE, DEFRESP, DEFSCRNHT, DEFSCRNWD, DELAY, DELETEQ, DEQ, "
          + "DESTCOUNT, DESTID, DESTIDLENG, DETAILLENGTH, DIGEST, DIGESTTYPE, DISCONNECT, DOCDELETE, DOCSIZE, DOCSTATUS, DOCTOKEN, "
          + "DOCUMENT, DS3270, DSSCS, DUMP, DUMPCODE, DUMPID, ECADDR, ECBLIST, EIB, ELEMNAME, ELEMNAMELEN, ELEMNS, ELEMNSLEN, END, "
          + "ENDACTIVITY, ENDBR, ENDBROWSE, ENDFILE, ENDOUTPUT, ENQ, ENTER, ENTRYNAME, EODS, EPRFIELD, EPRFROM, EPRINTO, EPRLENGTH, "
          + "EPRSET, EPRTYPE, ERASE, ERASEAUP, ERRTERM, ESMREASON, ESMRESP, EVENT, EVENTTYPE, EVENTUAL, EWASUPP, EXPECT, EXPIRYTIME, "
          + "EXTDS, EXTRACT, FACILITY, FACILITYTOKN, FAULTACTLEN, FAULTACTOR, FAULTCODE, FAULTCODELEN, FAULTCODESTR, FAULTSTRING,"
          + " FAULTSTRLEN, FCI, FCT, FIELD, FILE, FIRESTATUS, FLENGTH, FMH, FMHPARM, FORCE, FORMATTIME, FORMFEED, FORMFIELD, FREE, "
          + "FREEKB, FREEMAIN, FROMACTIVITY, FROMCCSID, FROMCHANNEL, FROMCODEPAGE, FROMDOC, FROMLENGTH, FROMPROCESS, FRSET, FULLDATE, "
          + "GCHARS, GCODES, GDS, GENERIC, GET, GETMAIN, GETNEXT, GMMI, GROUPID, GTEC, GTEQ, HANDLE, HEAD, HEADER, HEX, HILIGHT, HOLD, "
          + "HONEOM, HOST, HOSTCODEPAGE, HOSTLENGTH, HOSTTYPE, HOURS, HTTPHEADER, HTTPMETHOD, HTTPRNUM, HTTPVERSION, HTTPVNUM, IGNORE, "
          + "IMMEDIATE, INCREMENT, INCLUDE, INITIMG, INITPARM, INITPARMLEN, INPARTN, INPUTEVENT, INPUTMSG, INPUTMSGLEN, INQUIRE, INSERT, "
          + "INTERVAL, INTO, INTOCCSID, INTOCODEPAGE, INVALIDCOUNT, INVITE, INVOKINGPROG, ISSUE, ISSUER, ITEM, IUTYPE, JOURNALNAME, "
          + "JTYPEID, JUSFIRST, JUSLAST, JUSTIFY, KATAKANA, KEEP, KEYLENGTH, KEYNUMBER, L40, L64, L80, LANGINUSE, LANGUAGECODE, "
          + "LASTUSETIME, LDC, LDCMNEM, LDCNUM, LENGTHLIST, LEVEL, LIGHTPEN, LINK, LIST, LISTLENGTH, LLID, LOAD, LOCALITY, "
          + "LOCALITYLEN, LOGMESSAGE, LOGMODE, LOGONLOGMODE, LOGONMSG, LUNAME, MAIN, MAP, MAPCOLUMN, MAPHEIGHT, MAPLINE, MAPONLY, "
          + "MAPPED, MAPPINGDEV, MAPSET, MAPWIDTH, MASSINSERT, MAXDATALEN, MAXFLENGTH, MAXIMUM, MAXLENGTH, MAXLIFETIME, MAXPROCLEN, "
          + "MCC, MEDIATYPE, MESSAGEID, METADATA, METADATALEN, METHOD, METHODLENGTH, MILLISECONDS, MINIMUM, MINUTES, MMDDYY, MMDDYYYY, "
          + "MODENAME, MONITOR, MONTH, MONTHOFYEAR, MSR, MSRCONTROL, NAME, NAMELENGTH, NATLANG, NATLANGINUSE, NETNAME, NEWPASSWORD, "
          + "NEWPHRASE, NEWPHRASELEN, NEXTTRANSID, NLEOM, NOAUTOPAGE, NOCC, NOCHECK, NOCLICONVERT, NOCLOSE, NODATA, NODOCDELETE, "
          + "NODUMP, NOEDIT, NOFLUSH, NOHANDLE, NOINCONVERT, NONE, NOOUTCONERT, NOQUEUE, NOQUIESCE, NOSRVCONVERT, NOSUSPEND, NOTE, "
          + "NOTPURGEABLE, NOTRUNCATE, NOWAIT, NSCONTAINER, NUMCIPHERS, NUMEVENTS, NUMITEMS, NUMREC, NUMROUTES, NUMSEGMENTS, NUMTAB, "
          + "OIDCARD, OPCLASS, OPERATION, OPERATOR, OPERID, OPERKEYS, OPERPURGE, OPID, OPSECURITY, OPTIONS, ORGABCODE, ORGANIZATLEN,"
          + " ORGUNIT, ORGUNITLEN, OUTDESCR, OUTLINE, OUTPARTN, OWNER, PA, PAGENUM, PAGING, PARTN, PARTNER, PARTNPAGE, PARTNS, PARTNSET, "
          + "PASS, PASSBK, PASSWORD, PASSWORDLEN, PATH, PATHLENGTH, PCT, PFXLENG, PHRASE, PHRASELEN, PIPLENGTH, PIPLIST, POINT, "
          + "POOL, POP, PORTNUMBER, PORTNUMNU, POST, PPT, PREDICATE, PREFIX, PREPARE, PRINCONVID, PRINSYSID, PRINT, PRIORITY, "
          + "PRIVACY, PROCESS, PROCESSTYPE, PROCLENGTH, PROCNAME, PROFILE, PROGRAM, PROTECT, PS, PUNCH, PURGEABLE, PUSH, "
          + "PUT, QNAME, QUERY, QUERYPARM, QUERYSTRING, QUERYSTRLEN, RBA, RBN, READNEXT, READPREV, READQ, REATTACH, RECEIVER, "
          + "RECFM, RECORD, RECORDLEN, RECORDLENGTH, REDUCE, REFPARMS, REFPARMSLEN, RELATESINDEX, RELATESTYPE, RELATESURI, "
          + "REMOVE, REPEATABLE, REPETABLE, REPLY, REPLYLENGTH, REQID, REQUESTTYPE, RESCLASS, RESETBR, RESID, RESIDLENGTH, "
          + "RESOURCE, RESP, RESP2, RESSEC, RESTART, RESTYPE, RESULT, RESUME, RETAIN, RETCODE, RETCORD, RETRIECE, RETRIEVE, "
          + "RETURNPROG, RIDFLD, ROLE, ROLELENGTH, ROLLBACK, ROUTE, ROUTECODES, RPROCESS, RRESOURCE, RRN, RTERMID, RTRANSID, "
          + "SADDRLENGTH, SCHEME, SCHEMENAME, SCOPE, SCOPELEN, SCRNHT, SCRNWD, SECONDS, SEGMENTLIST, SENDER, SERIALNUM, "
          + "SERIALNUMLEN, SERVER, SERVERADDR, SERVERADDRNU, SERVERCONV, SERVERNAME, SESSION, SESSTOKEN, SHARED, SIGDATA, "
          + "SIGNOFF, SIGNON, SIT, SNAMELENGTH, SOAPFAULT, SOSI, SPOOLCLOSE, SPOOLOPEN, SPOOLREAD, SPOOLWRITE, SRVCONVERT, "
          + "SRVRADDR6NU, SRVRIPFAMILY, SSLTYPE, STARTBR, STARTBROWSE, STARTCODE, STATE, STATELEN, STATIONID, STATUSCODE, "
          + "STATUSLEN, STATUSTEXT, STORAGE, STRINGFORMAT, SUBADDR, SUBCODELEN, SUBCODESTR, SUBEVENT, SUSPEND, SUSPSTATUS, "
          + "SYMBOL, SYMBOLLIST, SYNCHRONOUS, SYNCLEVEL, SYNCONRETURN, SYNCPOINT, SYSID, TABLES, TASK, TASKPRIORITY, TCPIP, "
          + "TCPIPSERVICE, TCT, TCTUA, TCTUALENG, TD, TELLERID, TEMPLATE, TERMCODE, TERMID, TERMPRIORITY, TEXTKYBD, TEXTLENGTH, "
          + "TEXTPRINT, TIMEOUT, TIMER, TIMESEP, TOACTIVITY, TOCHANNEL, TOCONTAINER, TOFLENGTH, TOKEN, TOLENGTH, TOPROCESS, TRACE, "
          + "TRACENUM, TRAILER, TRANPRIORITY, TRANSACTION, TRANSFORM, TRANSID, TRIGGER, TRT, TS, TWA, TWALENG, TYPENAME, TYPENAMELEN, "
          + "TYPENS, TYPENSLEN, UNATTEND, UNCOMMITTED, UNESCAPED, UNLOCK, SQL, 'EXEC SQL', EXEC, UOW, UPDATE, URI, URIMAP, URL, "
          + "URLLENGTH, USERDATAKEY, USERID, USERNAME, USERNAMELEN, USERPRIORITY, VALIDATION, VALUELENGTH, VERIFY, VERSIONLEN, "
          + "VOLUME, VOLUMELENG, WAIT, WAITCICS, WEB, WPMEDIA, WRAP, WRITEQ, WSACONTEXT, WSAEPR, XCTL, XMLCONTAINER, XMLTODATA, "
          + "XMLTRANSFORM, XRBA, YEAR, YYDDD, YYDDMM, YYYYDDD, YYYYDDMM, YYYYMMDD, ZERO-DIGITAL, '.', "
          + "'01-49', '66', '77', '88', IDENTIFIER}";

  @Disabled("Needs changing the logic")
  @Test
  void test() {
    UseCaseEngine.runTest(
        TEXT,
        ImmutableList.of(new CobolText(NEW2_NAME, NEW2)),
        ImmutableMap.of(
            "1",
            new Diagnostic(
                null, MESSAGE, DiagnosticSeverity.Error, ErrorSource.PARSING.getText()),
            "2",
            new Diagnostic(
                null, MESSAGE2, DiagnosticSeverity.Error, ErrorSource.PARSING.getText())));
  }
}
