# Copyright (c) 2020 Broadcom.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Broadcom, Inc. - initial API and implementation

from inc.theia import zos_constants

SELF = None
THEIA = "Theia"
THEIA_APP_SHELL = "theia-app-shell"

CHE_LOGIN_ID = "kc-form-login"
CHE_SUBMIT = "kc-login"

IDE_IFRAME = "ide_iframe"

FILES_EXPLORER_TAB_ID = "shell-tab-explorer-view-container"
FILES_EXPLORER_ID = "explorer-view-container"

THEIA_LEFT_RIGHT_PANEL = "theia-left-right-split-panel"

SHELL_TAB_DEBUG = "shell-tab-debug"
THEIA_DEBUG = "debug"
THEIA_DEBUG_CONFIGURE = "theia-debug-configure"
THEIA_DEBUG_START = "theia-debug-start"
THEIA_DEBUG_STOP = "theia-debug-stop"
THEIA_DEBUG_STEP_OVER = "theia-debug-step-over"
THEIA_DEBUG_CONTINUE = "theia-debug-continue"
THEIA_DEBUG_TOP_STACK_FRAME = "theia-debug-top-stack-frame"
THEIA_DEBUG_TOP_STACK_FRAME_LINE = "theia-debug-top-stack-frame-line"
THEIA_DEBUG_THREAD = "theia-debug-thread"
THEIA_REMOVE_BREAKPOINTS_BUTTON = "debug.breakpoint.removeAll"
THEIA_SOURCE_BREAKPOINT = "theia-source-breakpoint"

THEIA_DEBUG_BREAKPOINT = "theia-debug-breakpoint"
THEIA_DEBUG_BREAKPOINT_HINT = "theia-debug-breakpoint-hint"
THEIA_DEBUG_CONSOLE_VARIABLE = "theia-debug-console-variable"

THEIA_HEADER = "theia-header"

FILES_PANEL_TITLE = "^Explorer.*$"
FILES_EXPLORER_CONTENT = "files"

THEIA_NOTIFICATION_CONTAINER = "theia-notifications-container"
THEIA_NOTIFICATION = "theia-notification-list-item"
THEIA_NOTIFICATIONS_CENTER = "theia-notification-center"
THEIA_NOTIFICATIONS_SHOW = "oction"
THEIA_NOTIFICATION_MESSAGE = "theia-notification-message"
THEIA_NOTIFICATION_ACTIONS = "theia-notification-actions"
THEIA_ACTION_ITEM = "action-item"
THEIA_ACTION_LABEL = "action-label"
THEIA_NOTIFICATION_CLOSE_BUTTON = "clear"
THEIA_NOTIFICATION_BUTTONS = "buttons"
THEIA_NOTIFICATION_BUTTON = "theia-button"
THEIA_VIEW_CONTAINER_TITLE_NODE = "theia-views-container-section-title"

THEIA_BOTTOM_SPLIT_PANEL = "theia-bottom-split-panel"
THEIA_MAIN_CONTENT_PANEL = "theia-main-content-panel"
THEIA_LEFT_CONTENT_PANEL = "theia-left-content-panel"
THEIA_DOCK_PANEL_WIDGET = "p-DockPanel-widget"
THEIA_DOCK_PANEL = "p-DockPanel"
THEIA_SIDE_PANEL_TOOLBAR = "theia-sidepanel-toolbar"
THEIA_SIDE_PANEL_TITLE = "theia-sidepanel-title"

THEIA_TAB_BAR = "p-TabBar"
THEIA_TABS = "p-TabBar-tab"
THEIA_TAB_CONTENT = "p-TabBar-content"
THEIA_TAB_LABEL = "p-TabBar-tabLabel"
THEIA_TAB_CLOSE_BUTTON = "p-TabBar-tabCloseIcon"

THEIA_TOP_PANEL = "theia-top-panel"
THEIA_MENU = "theia:menubar"
THEIA_MENU_CONTENT = "p-MenuBar-content"
THEIA_MENU_BAR_ITEMS = "p-MenuBar-item"
THEIA_MENU_BAR_ITEM_LABEL = "p-MenuBar-itemLabel"
THEIA_SUBMENU_CONTENT = "p-Menu-content"
THEIA_SUBMENU_ITEMS = "p-Menu-item"
THEIA_SUBMENU_ITEM_LABEL = "p-Menu-itemLabel"

THEIA_IFRAME = "pending-frame"

THEIA_TREE_EXPANDABLE_NODES = "theia-ExpandableTreeNode"
THEIA_TREE_NODES = "theia-TreeNode"
THEIA_DIR_NODE = "theia-DirNode"
THEIA_TREE_NODE_CONTENT = "theia-TreeNodeContent"
THEIA_TREE_CONTAINER = "theia-TreeContainer"
THEIA_TREE_NODE_SEGMENT_GROW = "theia-TreeNodeSegmentGrow"

THEIA_INLINE_ACTIONS = "theia-tree-view-inline-action"

THEIA_VIEWS_CONTAINER_SECTION_LABEL = "theia-views-container-section-label"
THEIA_EXPAND_ARROW = "theia-ExpansionToggle"

THEIA_USER_PREFERENCES = "code-editor-opener:user_storage:settings.json"

THEIA_STATUS_BAR = "theia-statusBar"
THEIA_STATUS_BAR_RIGHT_AREA = "right"
THEIA_STATUS_ELEMENTS_WITH_COMMANDS = "hasCommand"

THEIA_DIALOG_SHELL = "theia-dialog-shell"
THEIA_DIALOG_CONTROL = "dialogControl"
THEIA_DIALOG_TITLE = "dialogTitle"
THEIA_DIALOG_CONTENT = "dialogContent"
THEIA_DIALOG_SAVE_BUTTON = "Save"
THEIA_DIALOG_DONT_SAVE_BUTTON = "Don't save"
THEIA_DIALOG_CANCEL_BUTTON = "Cancel"

THEIA_F1_TITLE = "Type '?' to get help on the actions you can take from here"

WEB_VIEW_WIDGET = "webview-widget-%s"
WEB_VIEW_WIDGET_TAB = "shell-tab-" + WEB_VIEW_WIDGET

BROWSE_EDITOR_TITLE = "Untitled-%s"
BROWSE_EDITOR_ID = "code-editor-opener:untitled:/" + BROWSE_EDITOR_TITLE
BROWSE_EDITOR_TAB_ID = "shell-tab-" + BROWSE_EDITOR_ID

MONAKO_LINES_CONTENT = "view-lines"
MONAKO_EDITOR_LINE = "view-line"
MONAKO_LINE_NUMBERS = "line-numbers"
MONAKO_OVERLAYS = "view-overlays"
MONAKO_EDITOR_ERROR = "squiggly-error"
MONAKO_EDITOR_INFO = "squiggly-info"

MONAKO_CURRENT_LINE = "current-line"

MONAKO_QUICK_OPEN_OVERLAY = "quick-open-overlay"
MONAKO_QUICK_OPEN_CONTAINER = "quick-open-container"
MONAKO_QUICK_OPEN_INPUT = "quick-open-input"
MONAKO_OPEN_TREE = "quick-open-tree"
MONAKO_TREE_ROWS = "monaco-tree-rows"
MONAKO_TREE_ROW = "monaco-tree-row"
MONAKO_INPUT_CLASS = "input"
MONAKO_INPUT_WIDGET = "monaco-quick-open-widget"

MONAKO_SUGGEST_WIDGET = "suggest-widget"
MONAKO_LIST_ROWS = "monaco-list-rows"
MONAKO_LIST_ROW = "monaco-list-row"

MONAKO_ZONE_WIDGET = "zone-widget"

MONAKO_EDITOR_HOVER = "monaco-editor-hover"
MONAKO_EDITOR_HOVER_ROW = "hover-row"
MONAKO_HOVER_CONTENTS = "hover-contents"

ARIA_LABEL = "aria-label"
ARIA_HAS_POPUP = "aria-haspopup"
ARIA_HIDDEN = "aria-hidden"
ARIA_EXPANDED = "aria-expanded"

SCROLL_Y = "ps__rail-y"
SCROLL_Y_THUMB = "ps__thumb-y"

Ok = "Ok"
Close = "Close"
FILES = "Files"

# New Host WebForm
HOST_CFG_FORM = "hostCfg"
HOST_CFG_FORM_NEXT = "cliCKNext"
HOST_CFG_FORM_CONFIGURATIONS = "selectNumber"
HOST_CFG_FORM_ZOS_USER = "username"
HOST_CFG_FORM_PASSWORD = "password"
HOST_CFG_FORM_SUBMIT = "submitCredsButton"
HOST_CFG_FORM_NAME = "name"
HOST_CFG_FORM_URL = "url"
OK = "OK"

# Main menu constants
HelpAbout = "Theia"
Preferences = "Preferences"
Debug = "Debug"
Breakpoints = "Breakpoints"
NoBreakpoints = "No breakpoints"
Variables = "Variables"
DebugRemoveAllBreakpoints = "Remove All breakpoints"
SelectAll = "Select All"
Copy = "Copy"
Paste = "Paste"
Save = "Save"
TheiaDialog = "dialog"
TheiaTab = "tab"
LeftTab = "left_tab"

ELEMENT_TEXT = "element_text"
ELEMENT_TYPE = "element_type"
ELEMENT_TITLE = "title"
TYPE_ID = "id"
TYPE_NAME = "name"
TYPE_CLASS = "class"
TYPE_TAG = "tag"
TEXT_CLASS = "text"

SPAN = "span"

THEIA_UI = {
    CHE_LOGIN_ID: {
        ELEMENT_TEXT: CHE_LOGIN_ID,
        ELEMENT_TYPE: TYPE_ID
    },
    CHE_SUBMIT: {
        ELEMENT_TEXT: CHE_SUBMIT,
        ELEMENT_TYPE: TYPE_ID
    },
    IDE_IFRAME: {
        ELEMENT_TEXT: "ide-application-iframe",
        ELEMENT_TYPE: TYPE_ID
    },
    FILES_EXPLORER_ID: {
        ELEMENT_TEXT: FILES_EXPLORER_ID,
        ELEMENT_TYPE: TYPE_ID
    },
    THEIA_LEFT_RIGHT_PANEL: {
        ELEMENT_TEXT: THEIA_LEFT_RIGHT_PANEL,
        ELEMENT_TYPE: TYPE_ID
    },
    FILES_EXPLORER_TAB_ID: {
        ELEMENT_TEXT: FILES_EXPLORER_TAB_ID,
        ELEMENT_TYPE: TYPE_ID
    },
    SHELL_TAB_DEBUG: {
        ELEMENT_TEXT: SHELL_TAB_DEBUG,
        ELEMENT_TYPE: TYPE_ID
    },
    THEIA_DEBUG: {
        ELEMENT_TEXT: THEIA_DEBUG,
        ELEMENT_TYPE: TYPE_ID
    },
    THEIA_DEBUG_CONFIGURE: {
        ELEMENT_TEXT: THEIA_DEBUG_CONFIGURE,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_DEBUG_START: {
        ELEMENT_TEXT: THEIA_DEBUG_START,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_DEBUG_STOP: {
        ELEMENT_TEXT: THEIA_DEBUG_STOP,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_DEBUG_STEP_OVER: {
        ELEMENT_TEXT: THEIA_DEBUG_STEP_OVER,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_DEBUG_CONTINUE: {
        ELEMENT_TEXT: THEIA_DEBUG_CONTINUE,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_DEBUG_TOP_STACK_FRAME: {
        ELEMENT_TEXT: THEIA_DEBUG_TOP_STACK_FRAME,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_DEBUG_TOP_STACK_FRAME_LINE: {
        ELEMENT_TEXT: THEIA_DEBUG_TOP_STACK_FRAME_LINE,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_DEBUG_THREAD: {
        ELEMENT_TEXT: THEIA_DEBUG_THREAD,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_REMOVE_BREAKPOINTS_BUTTON: {
        ELEMENT_TEXT: THEIA_REMOVE_BREAKPOINTS_BUTTON,
        ELEMENT_TYPE: TYPE_ID
    },
    THEIA_SOURCE_BREAKPOINT: {
        ELEMENT_TEXT: THEIA_SOURCE_BREAKPOINT,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_DEBUG_BREAKPOINT: {
        ELEMENT_TEXT: THEIA_DEBUG_BREAKPOINT,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_DEBUG_BREAKPOINT_HINT: {
        ELEMENT_TEXT: THEIA_DEBUG_BREAKPOINT_HINT,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_DEBUG_CONSOLE_VARIABLE: {
        ELEMENT_TEXT: THEIA_DEBUG_CONSOLE_VARIABLE,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_HEADER: {
        ELEMENT_TEXT: THEIA_HEADER,
        ELEMENT_TYPE: TYPE_CLASS
    },
    FILES_EXPLORER_CONTENT: {
        ELEMENT_TEXT:FILES_EXPLORER_CONTENT,
        ELEMENT_TYPE: TYPE_ID
    },
    THEIA_APP_SHELL: {
        ELEMENT_TEXT: THEIA_APP_SHELL,
        ELEMENT_TYPE: TYPE_ID
    },
    THEIA_TAB_CONTENT: {
        ELEMENT_TEXT: THEIA_TAB_CONTENT,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_TOP_PANEL: {
        ELEMENT_TEXT: THEIA_TOP_PANEL,
        ELEMENT_TYPE: TYPE_ID
    },
    THEIA_MENU: {
        ELEMENT_TEXT: THEIA_MENU,
        ELEMENT_TYPE: TYPE_ID
    },
    THEIA_MENU_CONTENT: {
        ELEMENT_TEXT: THEIA_MENU_CONTENT,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_MENU_BAR_ITEMS: {
        ELEMENT_TEXT: THEIA_MENU_BAR_ITEMS,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_MENU_BAR_ITEM_LABEL: {
        ELEMENT_TEXT: THEIA_MENU_BAR_ITEM_LABEL,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_SUBMENU_CONTENT: {
        ELEMENT_TEXT: THEIA_SUBMENU_CONTENT,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_SUBMENU_ITEMS: {
        ELEMENT_TEXT: THEIA_SUBMENU_ITEMS,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_SUBMENU_ITEM_LABEL: {
        ELEMENT_TEXT: THEIA_SUBMENU_ITEM_LABEL,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_TAB_BAR: {
        ELEMENT_TEXT: THEIA_TAB_BAR,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_TABS: {
        ELEMENT_TEXT: THEIA_TABS,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_TAB_LABEL: {
        ELEMENT_TEXT: THEIA_TAB_LABEL,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_TAB_CLOSE_BUTTON: {
        ELEMENT_TEXT: THEIA_TAB_CLOSE_BUTTON,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_NOTIFICATION_CONTAINER: {
        ELEMENT_TEXT: THEIA_NOTIFICATION_CONTAINER,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_NOTIFICATIONS_CENTER: {
        ELEMENT_TEXT: THEIA_NOTIFICATIONS_CENTER,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_NOTIFICATION: {
        ELEMENT_TEXT: THEIA_NOTIFICATION,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_NOTIFICATIONS_SHOW: {
        ELEMENT_TEXT: THEIA_NOTIFICATIONS_SHOW,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_NOTIFICATION_MESSAGE: {
        ELEMENT_TEXT: THEIA_NOTIFICATION_MESSAGE,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_NOTIFICATION_ACTIONS: {
        ELEMENT_TEXT: THEIA_NOTIFICATION_ACTIONS,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_ACTION_ITEM: {
        ELEMENT_TEXT: THEIA_ACTION_ITEM,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_ACTION_LABEL: {
        ELEMENT_TEXT: THEIA_ACTION_LABEL,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_NOTIFICATION_CLOSE_BUTTON: {
        ELEMENT_TEXT: THEIA_NOTIFICATION_CLOSE_BUTTON,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_NOTIFICATION_BUTTONS: {
        ELEMENT_TEXT: THEIA_NOTIFICATION_BUTTONS,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_NOTIFICATION_BUTTON: {
        ELEMENT_TEXT: THEIA_NOTIFICATION_BUTTON,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_BOTTOM_SPLIT_PANEL: {
        ELEMENT_TEXT: THEIA_BOTTOM_SPLIT_PANEL,
        ELEMENT_TYPE: TYPE_ID
    },
    THEIA_MAIN_CONTENT_PANEL: {
        ELEMENT_TEXT: THEIA_MAIN_CONTENT_PANEL,
        ELEMENT_TYPE: TYPE_ID
    },
    THEIA_LEFT_CONTENT_PANEL: {
        ELEMENT_TEXT: THEIA_LEFT_CONTENT_PANEL,
        ELEMENT_TYPE: TYPE_ID
    },
    THEIA_DOCK_PANEL_WIDGET: {
        ELEMENT_TEXT: THEIA_DOCK_PANEL_WIDGET,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_DOCK_PANEL: {
        ELEMENT_TEXT: THEIA_DOCK_PANEL,
        ELEMENT_TYPE: TYPE_CLASS
    },
    zos_constants.ZOS_EXPLORER_CONTAINER: {
        ELEMENT_TEXT: zos_constants.ZOS_EXPLORER_CONTAINER,
        ELEMENT_TYPE: TYPE_ID
    },
    THEIA_VIEW_CONTAINER_TITLE_NODE: {
        ELEMENT_TEXT: THEIA_VIEW_CONTAINER_TITLE_NODE,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_EXPAND_ARROW: {
        ELEMENT_TEXT: THEIA_EXPAND_ARROW,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_STATUS_BAR: {
        ELEMENT_TEXT: THEIA_STATUS_BAR,
        ELEMENT_TYPE: TYPE_ID
    },
    THEIA_USER_PREFERENCES: {
        ELEMENT_TEXT: THEIA_USER_PREFERENCES,
        ELEMENT_TYPE: TYPE_ID
    },
    THEIA_STATUS_BAR_RIGHT_AREA: {
        ELEMENT_TEXT: THEIA_STATUS_BAR_RIGHT_AREA,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_STATUS_ELEMENTS_WITH_COMMANDS: {
        ELEMENT_TEXT: THEIA_STATUS_ELEMENTS_WITH_COMMANDS,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_DIALOG_SHELL: {
        ELEMENT_TEXT: THEIA_DIALOG_SHELL,
        ELEMENT_TYPE: TYPE_ID
    },
    THEIA_DIALOG_CONTROL: {
        ELEMENT_TEXT: THEIA_DIALOG_CONTROL,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_DIALOG_TITLE: {
        ELEMENT_TEXT: THEIA_DIALOG_TITLE,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_DIALOG_CONTENT: {
        ELEMENT_TEXT: THEIA_DIALOG_CONTENT,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_IFRAME: {
        ELEMENT_TEXT: THEIA_IFRAME,
        ELEMENT_TYPE: TYPE_ID
    },
    HOST_CFG_FORM: {
        ELEMENT_TEXT: HOST_CFG_FORM,
        ELEMENT_TYPE: TYPE_ID
    },
    HOST_CFG_FORM_NAME: {
        ELEMENT_TEXT: HOST_CFG_FORM_NAME,
        ELEMENT_TYPE: TYPE_ID
    },
    HOST_CFG_FORM_URL: {
        ELEMENT_TEXT: HOST_CFG_FORM_URL,
        ELEMENT_TYPE: TYPE_ID
    },
    HOST_CFG_FORM_ZOS_USER: {
        ELEMENT_TEXT: HOST_CFG_FORM_ZOS_USER,
        ELEMENT_TYPE: TYPE_ID
    },
    HOST_CFG_FORM_PASSWORD: {
        ELEMENT_TEXT: HOST_CFG_FORM_PASSWORD,
        ELEMENT_TYPE: TYPE_ID
    },
    HOST_CFG_FORM_SUBMIT: {
        ELEMENT_TEXT: HOST_CFG_FORM_SUBMIT,
        ELEMENT_TYPE: TYPE_ID
    },
    HOST_CFG_FORM_NEXT: {
        ELEMENT_TEXT: HOST_CFG_FORM_NEXT,
        ELEMENT_TYPE: TYPE_ID
    },
    zos_constants.ZOS_EXPLORER_ID: {
        ELEMENT_TEXT: zos_constants.ZOS_EXPLORER_ID,
        ELEMENT_TYPE: TYPE_ID
    },
    zos_constants.ZOS_EXPLORER_LABEL: {
        ELEMENT_TEXT: zos_constants.ZOS_EXPLORER_LABEL,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_TREE_EXPANDABLE_NODES: {
        ELEMENT_TEXT: THEIA_TREE_EXPANDABLE_NODES,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_TREE_NODES: {
        ELEMENT_TEXT: THEIA_TREE_NODES,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_TREE_NODE_CONTENT: {
        ELEMENT_TEXT: THEIA_TREE_NODE_CONTENT,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_TREE_CONTAINER: {
        ELEMENT_TEXT: THEIA_TREE_CONTAINER,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_TREE_NODE_SEGMENT_GROW: {
        ELEMENT_TEXT: THEIA_TREE_NODE_SEGMENT_GROW,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_INLINE_ACTIONS: {
        ELEMENT_TEXT: THEIA_INLINE_ACTIONS,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_SIDE_PANEL_TITLE: {
        ELEMENT_TEXT: THEIA_SIDE_PANEL_TITLE,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_SIDE_PANEL_TOOLBAR: {
        ELEMENT_TEXT: THEIA_SIDE_PANEL_TOOLBAR,
        ELEMENT_TYPE: TYPE_CLASS
    },
    THEIA_VIEWS_CONTAINER_SECTION_LABEL: {
        ELEMENT_TEXT: THEIA_VIEWS_CONTAINER_SECTION_LABEL,
        ELEMENT_TYPE: TYPE_CLASS
    },
    TEXT_CLASS: {
        ELEMENT_TEXT: TEXT_CLASS,
        ELEMENT_TYPE: TYPE_CLASS
    },
    SPAN: {
        ELEMENT_TEXT: SPAN,
        ELEMENT_TYPE: TYPE_TAG
    },
    MONAKO_QUICK_OPEN_OVERLAY: {
        ELEMENT_TEXT: MONAKO_QUICK_OPEN_OVERLAY,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_QUICK_OPEN_CONTAINER: {
        ELEMENT_TEXT: MONAKO_QUICK_OPEN_CONTAINER,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_QUICK_OPEN_INPUT: {
        ELEMENT_TEXT: MONAKO_QUICK_OPEN_INPUT,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_INPUT_WIDGET: {
        ELEMENT_TEXT: MONAKO_INPUT_WIDGET,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_SUGGEST_WIDGET: {
        ELEMENT_TEXT: MONAKO_SUGGEST_WIDGET,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_LIST_ROWS: {
        ELEMENT_TEXT: MONAKO_LIST_ROWS,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_LIST_ROW: {
        ELEMENT_TEXT: MONAKO_LIST_ROW,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_ZONE_WIDGET: {
        ELEMENT_TEXT: MONAKO_ZONE_WIDGET,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_EDITOR_HOVER: {
        ELEMENT_TEXT: MONAKO_EDITOR_HOVER,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_EDITOR_HOVER_ROW: {
        ELEMENT_TEXT: MONAKO_EDITOR_HOVER_ROW,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_HOVER_CONTENTS: {
        ELEMENT_TEXT: MONAKO_HOVER_CONTENTS,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_OPEN_TREE: {
        ELEMENT_TEXT: MONAKO_OPEN_TREE,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_TREE_ROWS: {
        ELEMENT_TEXT: MONAKO_TREE_ROWS,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_TREE_ROW: {
        ELEMENT_TEXT: MONAKO_TREE_ROW,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_INPUT_CLASS: {
        ELEMENT_TEXT: MONAKO_INPUT_CLASS,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_LINES_CONTENT: {
        ELEMENT_TEXT: MONAKO_LINES_CONTENT,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_EDITOR_LINE: {
        ELEMENT_TEXT: MONAKO_EDITOR_LINE,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_LINE_NUMBERS: {
        ELEMENT_TEXT: MONAKO_LINE_NUMBERS,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_OVERLAYS: {
        ELEMENT_TEXT: MONAKO_OVERLAYS,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_EDITOR_ERROR: {
        ELEMENT_TEXT: MONAKO_EDITOR_ERROR,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_EDITOR_INFO: {
        ELEMENT_TEXT: MONAKO_EDITOR_INFO,
        ELEMENT_TYPE: TYPE_CLASS
    },
    MONAKO_CURRENT_LINE: {
        ELEMENT_TEXT: MONAKO_CURRENT_LINE,
        ELEMENT_TYPE: TYPE_CLASS
    },
    SCROLL_Y: {
        ELEMENT_TEXT: SCROLL_Y,
        ELEMENT_TYPE: TYPE_CLASS
    },
    SCROLL_Y_THUMB: {
        ELEMENT_TEXT: SCROLL_Y_THUMB,
        ELEMENT_TYPE: TYPE_CLASS
    }
}

DEFAULT_TINY_TIMEOUT = 5
DEFAULT_SHORT_TIMEOUT = 10
DEFAULT_TIMEOUT = 30
DEFAULT_LONG_TIMEOUT = 60
DEFAULT_HUGE_TIMEOUT = 180

THEIA_ENABLED = "enabled"
STATE_VISIBLE = "visible"
STATE_HIDDEN = "hidden"
THEIA_ELEMENT_COLLAPSED = "theia-mod-collapsed"
THEIA_CURRENT_TAB = "p-mod-current"
THEIA_HIDDEN = "p-mod-hidden"
THEIA_CLOSED = "closed"
THEIA_UNSAVED_FILE = "theia-mod-dirty"
THEIA_FOCUSED = "focused"
THEIA_LOCALS = "Locals"
THEIA_MOD_DISABLED = "theia-mod-disabled"
